/**
 * Offline emoji catalogue for the marker picker. GENERATED FILE — do not edit by
 * hand; run `node scripts/generate-emoji-data.mjs` after changing that table.
 *
 * The plugin deliberately ships this list instead of depending on an npm emoji
 * package: every `dependency` lands in `main.js`, which the release pipeline
 * caps at 10 MiB, and the picker must work fully offline.
 *
 * Field names are short because the whole table is a bundle-size decision:
 * - `g` the glyph that gets stored as the marker value
 * - `n` English name, also the accessible label
 * - `k` search keywords; Simplified Chinese terms come first so both languages
 *       can find the emoji
 * - `c` category id, used for the "all" order and the empty-result hint
 *
 * 1299 entries.
 */
export interface EmojiCatalogEntry {
  readonly g: string;
  readonly n: string;
  readonly k: string;
  readonly c: string;
}

export const EMOJI_CATALOG: readonly EmojiCatalogEntry[] = [
  { g: "😀", n: "grinning face", k: "笑脸 开心 高兴 笑", c: "smileys-emotion" },
  { g: "😃", n: "grinning face with big eyes", k: "笑脸 大笑 开心 微笑 高兴", c: "smileys-emotion" },
  { g: "😄", n: "grinning face with smiling eyes", k: "开心 笑 眯眼笑", c: "smileys-emotion" },
  { g: "😁", n: "beaming face with smiling eyes", k: "开心 笑 露齿笑", c: "smileys-emotion" },
  { g: "😆", n: "grinning squinting face", k: "大笑 露齿 眯眼", c: "smileys-emotion" },
  { g: "😅", n: "grinning face with sweat", k: "苦笑 出汗 尴尬", c: "smileys-emotion" },
  { g: "🤣", n: "rolling on the floor laughing", k: "笑翻 大笑 爆笑 笑死", c: "smileys-emotion" },
  { g: "😂", n: "face with tears of joy", k: "笑哭 笑死 感动 流泪笑", c: "smileys-emotion" },
  { g: "🙂", n: "slightly smiling face", k: "微笑 浅笑 礼貌", c: "smileys-emotion" },
  { g: "🙃", n: "upside-down face", k: "颠倒 反了 无语 滑稽", c: "smileys-emotion" },
  { g: "🫠", n: "melting face", k: "融化 崩溃 无奈 心累", c: "smileys-emotion" },
  { g: "😉", n: "winking face", k: "眨眼 调皮 暗示", c: "smileys-emotion" },
  { g: "😊", n: "smiling face with smiling eyes", k: "微笑 开心 善良", c: "smileys-emotion" },
  { g: "🥰", n: "smiling face with hearts", k: "爱心眼 喜欢 幸福 崇拜", c: "smileys-emotion" },
  { g: "😍", n: "smiling face with heart-eyes", k: "爱心眼 喜爱 迷恋", c: "smileys-emotion" },
  { g: "🤩", n: "star-struck", k: "星星眼 崇拜 惊艳 追星", c: "smileys-emotion" },
  { g: "😘", n: "face blowing a kiss", k: "飞吻 亲亲 爱", c: "smileys-emotion" },
  { g: "😗", n: "kissing face", k: "亲吻 亲亲", c: "smileys-emotion" },
  { g: "☺", n: "smiling face", k: "微笑 平静 含蓄", c: "smileys-emotion" },
  { g: "😚", n: "kissing face with closed eyes", k: "亲吻 闭眼 亲亲", c: "smileys-emotion" },
  { g: "😙", n: "kissing face with smiling eyes", k: "亲吻 微笑 亲亲", c: "smileys-emotion" },
  { g: "🥲", n: "smiling face with tear", k: "含泪微笑 感激 坚强", c: "smileys-emotion" },
  { g: "😋", n: "face savoring food", k: "好吃 美味 馋 舔嘴", c: "smileys-emotion" },
  { g: "😛", n: "face with tongue", k: "吐舌 调皮", c: "smileys-emotion" },
  { g: "😜", n: "winking face with tongue", k: "吐舌眨眼 调皮 开玩笑", c: "smileys-emotion" },
  { g: "🤪", n: "zany face", k: "疯狂 搞怪 发疯", c: "smileys-emotion" },
  { g: "😝", n: "squinting face with tongue", k: "吐舌眯眼 搞怪 调皮", c: "smileys-emotion" },
  { g: "🤑", n: "money-mouth face", k: "发财 有钱 贪财 美元", c: "smileys-emotion" },
  { g: "🤗", n: "smiling face with open hands", k: "拥抱 抱抱 支持", c: "smileys-emotion" },
  { g: "🤭", n: "face with hand over mouth", k: "捂嘴 偷笑 惊讶", c: "smileys-emotion" },
  { g: "🫢", n: "face with open eyes and hand over mouth", k: "惊讶 捂嘴 震惊", c: "smileys-emotion" },
  { g: "🫣", n: "face with peeking eye", k: "偷看 害怕 好奇", c: "smileys-emotion" },
  { g: "🤫", n: "shushing face", k: "嘘 安静 保密", c: "smileys-emotion" },
  { g: "🤔", n: "thinking face", k: "思考 想 疑惑 琢磨", c: "smileys-emotion" },
  { g: "🫡", n: "saluting face", k: "敬礼 致敬 收到", c: "smileys-emotion" },
  { g: "🤐", n: "zipper-mouth face", k: "闭嘴 保密 不说话", c: "smileys-emotion" },
  { g: "🤨", n: "face with raised eyebrow", k: "挑眉 怀疑 疑惑 质疑", c: "smileys-emotion" },
  { g: "😐", n: "neutral face", k: "无语 面无表情 平静", c: "smileys-emotion" },
  { g: "😑", n: "expressionless face", k: "无语 面无表情", c: "smileys-emotion" },
  { g: "😶", n: "face without mouth", k: "沉默 无语 无话可说", c: "smileys-emotion" },
  { g: "🫥", n: "dotted line face", k: "隐身 消失 透明", c: "smileys-emotion" },
  { g: "😏", n: "smirking face", k: "得意 坏笑 自满", c: "smileys-emotion" },
  { g: "😒", n: "unamused face", k: "不爽 不满 无语", c: "smileys-emotion" },
  { g: "🙄", n: "face with rolling eyes", k: "翻白眼 无语 鄙视", c: "smileys-emotion" },
  { g: "😬", n: "grimacing face", k: "龇牙 尴尬 难受", c: "smileys-emotion" },
  { g: "😮", n: "face with open mouth", k: "惊讶 张嘴 吃惊", c: "smileys-emotion" },
  { g: "😯", n: "hushed face", k: "惊讶 震惊 安静", c: "smileys-emotion" },
  { g: "😲", n: "astonished face", k: "惊讶 震惊 呆住", c: "smileys-emotion" },
  { g: "😳", n: "flushed face", k: "脸红 害羞 尴尬", c: "smileys-emotion" },
  { g: "🥺", n: "pleading face", k: "恳求 委屈 可怜 拜托", c: "smileys-emotion" },
  { g: "🥹", n: "face holding back tears", k: "忍住眼泪 感动 委屈", c: "smileys-emotion" },
  { g: "😦", n: "frowning face with open mouth", k: "难过 惊讶 张大嘴", c: "smileys-emotion" },
  { g: "😧", n: "anguished face", k: "痛苦 难受 焦急", c: "smileys-emotion" },
  { g: "😨", n: "fearful face", k: "害怕 恐惧 担心", c: "smileys-emotion" },
  { g: "😰", n: "anxious face with sweat", k: "紧张 冷汗 焦虑", c: "smileys-emotion" },
  { g: "😥", n: "sad but relieved face", k: "松了口气 释然 汗", c: "smileys-emotion" },
  { g: "😢", n: "crying face", k: "哭 流泪 伤心", c: "smileys-emotion" },
  { g: "😭", n: "loudly crying face", k: "大哭 痛哭 伤心 崩溃", c: "smileys-emotion" },
  { g: "😱", n: "face screaming in fear", k: "尖叫 恐惧 害怕 惊悚", c: "smileys-emotion" },
  { g: "😖", n: "confounded face", k: "困惑 纠结 难受", c: "smileys-emotion" },
  { g: "😣", n: "persevering face", k: "坚持 忍耐 难受", c: "smileys-emotion" },
  { g: "😞", n: "disappointed face", k: "失望 沮丧 难过", c: "smileys-emotion" },
  { g: "😓", n: "downcast face with sweat", k: "低落 汗 泄气", c: "smileys-emotion" },
  { g: "😩", n: "weary face", k: "疲惫 累 沮丧", c: "smileys-emotion" },
  { g: "😫", n: "tired face", k: "疲惫 累 困", c: "smileys-emotion" },
  { g: "🥱", n: "yawning face", k: "打哈欠 困 无聊", c: "smileys-emotion" },
  { g: "😤", n: "face with steam from nose", k: "生气 愤怒 哼", c: "smileys-emotion" },
  { g: "😡", n: "enraged face", k: "愤怒 生气 暴怒", c: "smileys-emotion" },
  { g: "😠", n: "angry face", k: "生气 愤怒 不满", c: "smileys-emotion" },
  { g: "🤬", n: "face with symbols on mouth", k: "骂人 生气 爆粗", c: "smileys-emotion" },
  { g: "😈", n: "smiling face with horns", k: "恶魔 坏笑 调皮", c: "smileys-emotion" },
  { g: "👿", n: "angry face with horns", k: "恶魔 生气 坏", c: "smileys-emotion" },
  { g: "💀", n: "skull", k: "骷髅 死亡 完了", c: "smileys-emotion" },
  { g: "☠", n: "skull and crossbones", k: "骷髅 危险 毒", c: "smileys-emotion" },
  { g: "💩", n: "pile of poo", k: "便便 屎 糟糕", c: "smileys-emotion" },
  { g: "🤡", n: "clown face", k: "小丑 搞笑 荒唐", c: "smileys-emotion" },
  { g: "👹", n: "ogre", k: "食人魔 怪物 鬼", c: "smileys-emotion" },
  { g: "👺", n: "goblin", k: "小妖精 怪物 鬼", c: "smileys-emotion" },
  { g: "👻", n: "ghost", k: "幽灵 鬼 吓人", c: "smileys-emotion" },
  { g: "👽", n: "alien", k: "外星人 太空 异形", c: "smileys-emotion" },
  { g: "👾", n: "alien monster", k: "外星怪物 游戏 像素", c: "smileys-emotion" },
  { g: "🤖", n: "robot", k: "机器人 机械 自动", c: "smileys-emotion" },
  { g: "😺", n: "grinning cat", k: "猫 开心 笑脸", c: "smileys-emotion" },
  { g: "😸", n: "grinning cat with smiling eyes", k: "猫 笑 开心", c: "smileys-emotion" },
  { g: "😹", n: "cat with tears of joy", k: "猫 笑哭", c: "smileys-emotion" },
  { g: "😻", n: "smiling cat with heart-eyes", k: "猫 爱心 喜欢", c: "smileys-emotion" },
  { g: "😼", n: "cat with wry smile", k: "猫 坏笑 得意", c: "smileys-emotion" },
  { g: "😽", n: "kissing cat", k: "猫 亲亲", c: "smileys-emotion" },
  { g: "🙀", n: "weary cat", k: "猫 惊讶 疲惫", c: "smileys-emotion" },
  { g: "😿", n: "crying cat", k: "猫 哭 伤心", c: "smileys-emotion" },
  { g: "😾", n: "pouting cat", k: "猫 生气 不满", c: "smileys-emotion" },
  { g: "🙈", n: "see-no-evil monkey", k: "猴子 不看 捂眼", c: "smileys-emotion" },
  { g: "🙉", n: "hear-no-evil monkey", k: "猴子 不听 捂耳", c: "smileys-emotion" },
  { g: "🙊", n: "speak-no-evil monkey", k: "猴子 不说 捂嘴", c: "smileys-emotion" },
  { g: "💌", n: "love letter", k: "情书 爱 信", c: "smileys-emotion" },
  { g: "💘", n: "heart with arrow", k: "爱心 箭 恋爱", c: "smileys-emotion" },
  { g: "💝", n: "heart with ribbon", k: "爱心 礼物 丝带", c: "smileys-emotion" },
  { g: "💖", n: "sparkling heart", k: "爱心 闪亮 喜欢", c: "smileys-emotion" },
  { g: "💗", n: "growing heart", k: "爱心 变心 喜欢", c: "smileys-emotion" },
  { g: "💓", n: "beating heart", k: "心跳 爱心 喜欢", c: "smileys-emotion" },
  { g: "💞", n: "revolving hearts", k: "爱心 环绕 恋爱", c: "smileys-emotion" },
  { g: "💕", n: "two hearts", k: "两颗心 恋爱 喜欢", c: "smileys-emotion" },
  { g: "💟", n: "heart decoration", k: "爱心 装饰", c: "smileys-emotion" },
  { g: "❣", n: "heart exclamation", k: "爱心 感叹 爱心感叹", c: "smileys-emotion" },
  { g: "💔", n: "broken heart", k: "心碎 失恋 伤心", c: "smileys-emotion" },
  { g: "❤", n: "red heart", k: "红心 爱 喜欢", c: "smileys-emotion" },
  { g: "🩷", n: "pink heart", k: "粉心 喜欢 爱", c: "smileys-emotion" },
  { g: "🧡", n: "orange heart", k: "橙心 喜欢 爱", c: "smileys-emotion" },
  { g: "💛", n: "yellow heart", k: "黄心 友情 喜欢", c: "smileys-emotion" },
  { g: "💚", n: "green heart", k: "绿心 喜欢 爱", c: "smileys-emotion" },
  { g: "💙", n: "blue heart", k: "蓝心 喜欢 爱", c: "smileys-emotion" },
  { g: "💜", n: "purple heart", k: "紫心 喜欢 爱", c: "smileys-emotion" },
  { g: "🖤", n: "black heart", k: "黑心 喜欢 暗", c: "smileys-emotion" },
  { g: "🤍", n: "white heart", k: "白心 喜欢", c: "smileys-emotion" },
  { g: "🤎", n: "brown heart", k: "棕心 喜欢", c: "smileys-emotion" },
  { g: "💯", n: "hundred points", k: "满分 一百分 完美", c: "smileys-emotion" },
  { g: "💢", n: "anger symbol", k: "怒气 生气 冲突", c: "smileys-emotion" },
  { g: "💥", n: "collision", k: "碰撞 爆炸 冲突", c: "smileys-emotion" },
  { g: "💫", n: "dizzy", k: "眩晕 头晕 混乱", c: "smileys-emotion" },
  { g: "💬", n: "speech balloon", k: "对话 说话 评论", c: "smileys-emotion" },
  { g: "💭", n: "thought balloon", k: "想法 思考 内心", c: "smileys-emotion" },
  { g: "💤", n: "sleeping", k: "睡觉 睡眠 困", c: "smileys-emotion" },
  { g: "💨", n: "dashing away", k: "快跑 冲刺 溜走", c: "smileys-emotion" },
  { g: "👋", n: "waving hand", k: "挥手 你好 再见", c: "people-body" },
  { g: "🤚", n: "raised back of hand", k: "手背 举起", c: "people-body" },
  { g: "🖐", n: "hand with fingers splayed", k: "张开手 五指", c: "people-body" },
  { g: "✋", n: "raised hand", k: "举手 停止 打招呼", c: "people-body" },
  { g: "🖖", n: "vulcan salute", k: "瓦肯 举手 星际", c: "people-body" },
  { g: "👌", n: "OK hand", k: "OK 好的 没问题 可以", c: "people-body" },
  { g: "🤌", n: "pinched fingers", k: "捏手 手势 什么意思", c: "people-body" },
  { g: "🤏", n: "pinching hand", k: "一点点 少量 手势", c: "people-body" },
  { g: "✌", n: "victory hand", k: "胜利 耶 剪刀手", c: "people-body" },
  { g: "🤞", n: "crossed fingers", k: "好运 祈祷 期待", c: "people-body" },
  { g: "🫰", n: "hand with index finger and thumb crossed", k: "比心 爱心 手势", c: "people-body" },
  { g: "🤟", n: "love-you gesture", k: "爱你 手势 比心", c: "people-body" },
  { g: "🤘", n: "sign of the horns", k: "摇滚 角 手势", c: "people-body" },
  { g: "🤙", n: "call me hand", k: "打电话 联系 手势", c: "people-body" },
  { g: "👈", n: "backhand index pointing left", k: "指左 左边 指示", c: "people-body" },
  { g: "👉", n: "backhand index pointing right", k: "指右 右边 指示", c: "people-body" },
  { g: "👆", n: "backhand index pointing up", k: "指上 上面 指示", c: "people-body" },
  { g: "🖕", n: "middle finger", k: "中指 生气 挑衅", c: "people-body" },
  { g: "👇", n: "backhand index pointing down", k: "指下 下面 指示", c: "people-body" },
  { g: "☝", n: "index pointing up", k: "指上 提醒 注意", c: "people-body" },
  { g: "🫱", n: "rightwards hand", k: "向右的手 牵手 握手", c: "people-body" },
  { g: "🫲", n: "leftwards hand", k: "向左的手 牵手 握手", c: "people-body" },
  { g: "🫳", n: "palm down hand", k: "手心向下 放下", c: "people-body" },
  { g: "🫴", n: "palm up hand", k: "手心向上 请求 托举", c: "people-body" },
  { g: "👍", n: "thumbs up", k: "点赞 赞 好的 同意", c: "people-body" },
  { g: "👎", n: "thumbs down", k: "差评 反对 不好 不行", c: "people-body" },
  { g: "👊", n: "oncoming fist", k: "拳头 加油 击拳", c: "people-body" },
  { g: "🤛", n: "left-facing fist", k: "拳头 碰拳", c: "people-body" },
  { g: "🤜", n: "right-facing fist", k: "拳头 碰拳", c: "people-body" },
  { g: "👏", n: "clapping hands", k: "鼓掌 拍手 棒", c: "people-body" },
  { g: "🙌", n: "raising hands", k: "举手 万岁 庆祝", c: "people-body" },
  { g: "🫶", n: "heart hands", k: "比心 爱心 双手", c: "people-body" },
  { g: "👐", n: "open hands", k: "张开双手 拥抱 什么", c: "people-body" },
  { g: "🤲", n: "palms up together", k: "双手合十 请 托付", c: "people-body" },
  { g: "🤝", n: "handshake", k: "握手 合作 达成", c: "people-body" },
  { g: "🙏", n: "folded hands", k: "祈祷 拜托 感谢 合十", c: "people-body" },
  { g: "✍", n: "writing hand", k: "写字 记录 笔记", c: "people-body" },
  { g: "💅", n: "nail polish", k: "指甲油 美甲 化妆", c: "people-body" },
  { g: "🤳", n: "selfie", k: "自拍 拍照 手机", c: "people-body" },
  { g: "💪", n: "flexed biceps", k: "肌肉 加油 强壮 力量", c: "people-body" },
  { g: "🦾", n: "mechanical arm", k: "机械臂 假肢 科技", c: "people-body" },
  { g: "🦿", n: "mechanical leg", k: "机械腿 假肢 科技", c: "people-body" },
  { g: "🦵", n: "leg", k: "腿 脚", c: "people-body" },
  { g: "🦶", n: "foot", k: "脚 足", c: "people-body" },
  { g: "👂", n: "ear", k: "耳朵 听", c: "people-body" },
  { g: "🦻", n: "ear with hearing aid", k: "助听器 耳朵 听力", c: "people-body" },
  { g: "👃", n: "nose", k: "鼻子 闻", c: "people-body" },
  { g: "🧠", n: "brain", k: "大脑 智慧 思考", c: "people-body" },
  { g: "🫀", n: "anatomical heart", k: "心脏 器官 健康", c: "people-body" },
  { g: "🫁", n: "lungs", k: "肺 器官 呼吸", c: "people-body" },
  { g: "🦷", n: "tooth", k: "牙齿 口腔", c: "people-body" },
  { g: "🦴", n: "bone", k: "骨头 骨骼", c: "people-body" },
  { g: "👀", n: "eyes", k: "眼睛 看 关注", c: "people-body" },
  { g: "👁", n: "eye", k: "眼睛 看 观察", c: "people-body" },
  { g: "👅", n: "tongue", k: "舌头 尝", c: "people-body" },
  { g: "👄", n: "mouth", k: "嘴 说话", c: "people-body" },
  { g: "👤", n: "bust in silhouette", k: "人像 用户 匿名 剪影", c: "people-body" },
  { g: "👥", n: "busts in silhouette", k: "人像 多人 团队", c: "people-body" },
  { g: "🫂", n: "people hugging", k: "拥抱 安慰 支持", c: "people-body" },
  { g: "👣", n: "footprints", k: "脚印 足迹 走过", c: "people-body" },
  { g: "👶", n: "baby", k: "婴儿 宝宝 小孩", c: "people-body" },
  { g: "🧒", n: "child", k: "小孩 儿童", c: "people-body" },
  { g: "👦", n: "boy", k: "男孩 儿子", c: "people-body" },
  { g: "👧", n: "girl", k: "女孩 女儿", c: "people-body" },
  { g: "🧑", n: "person", k: "人 人物", c: "people-body" },
  { g: "👱", n: "person blond hair", k: "金发 人", c: "people-body" },
  { g: "👨", n: "man", k: "男人 男性", c: "people-body" },
  { g: "🧔", n: "person beard", k: "胡须 人", c: "people-body" },
  { g: "👩", n: "woman", k: "女人 女性", c: "people-body" },
  { g: "🧓", n: "older person", k: "老人 长者", c: "people-body" },
  { g: "👴", n: "old man", k: "老人 爷爷", c: "people-body" },
  { g: "👵", n: "old woman", k: "老人 奶奶", c: "people-body" },
  { g: "🙍", n: "person frowning", k: "皱眉 不满", c: "people-body" },
  { g: "🙎", n: "person pouting", k: "撅嘴 不满", c: "people-body" },
  { g: "🙅", n: "person gesturing NO", k: "拒绝 不行", c: "people-body" },
  { g: "🙆", n: "person gesturing OK", k: "可以 同意", c: "people-body" },
  { g: "💁", n: "person tipping hand", k: "举手 服务 无所谓", c: "people-body" },
  { g: "🙋", n: "person raising hand", k: "举手 提问 报名", c: "people-body" },
  { g: "🧏", n: "deaf person", k: "听障 手语", c: "people-body" },
  { g: "🙇", n: "person bowing", k: "鞠躬 道歉 感谢", c: "people-body" },
  { g: "🤦", n: "person facepalming", k: "捂脸 无奈 无语", c: "people-body" },
  { g: "🤷", n: "person shrugging", k: "耸肩 不知道 无所谓", c: "people-body" },
  { g: "👮", n: "police officer", k: "警察 民警", c: "people-body" },
  { g: "🕵", n: "detective", k: "侦探 调查", c: "people-body" },
  { g: "💂", n: "guard", k: "卫兵 保安", c: "people-body" },
  { g: "🥷", n: "ninja", k: "忍者 隐身", c: "people-body" },
  { g: "👷", n: "construction worker", k: "建筑工人 施工", c: "people-body" },
  { g: "🤴", n: "prince", k: "王子 皇室", c: "people-body" },
  { g: "👸", n: "princess", k: "公主 皇室", c: "people-body" },
  { g: "👳", n: "person wearing turban", k: "头巾 人", c: "people-body" },
  { g: "👲", n: "person with skullcap", k: "帽子 人", c: "people-body" },
  { g: "🤵", n: "person in tuxedo", k: "礼服 婚礼 正式", c: "people-body" },
  { g: "👰", n: "person with veil", k: "头纱 婚礼 新娘", c: "people-body" },
  { g: "🤰", n: "pregnant woman", k: "怀孕 孕妇", c: "people-body" },
  { g: "🫃", n: "pregnant man", k: "怀孕 男性", c: "people-body" },
  { g: "🫄", n: "pregnant person", k: "怀孕 人", c: "people-body" },
  { g: "🤱", n: "breast-feeding", k: "哺乳 母婴", c: "people-body" },
  { g: "👼", n: "baby angel", k: "天使 宝宝", c: "people-body" },
  { g: "🎅", n: "Santa Claus", k: "圣诞老人 圣诞", c: "people-body" },
  { g: "🤶", n: "Mrs. Claus", k: "圣诞奶奶 圣诞", c: "people-body" },
  { g: "🦸", n: "superhero", k: "超级英雄 英雄", c: "people-body" },
  { g: "🦹", n: "supervillain", k: "反派 坏蛋", c: "people-body" },
  { g: "🧙", n: "mage", k: "法师 魔法", c: "people-body" },
  { g: "🧚", n: "fairy", k: "仙女 精灵", c: "people-body" },
  { g: "🧛", n: "vampire", k: "吸血鬼 万圣节", c: "people-body" },
  { g: "🧜", n: "merperson", k: "美人鱼 人鱼", c: "people-body" },
  { g: "🧝", n: "elf", k: "精灵 小精灵", c: "people-body" },
  { g: "🧞", n: "genie", k: "精灵 神灯", c: "people-body" },
  { g: "🧟", n: "zombie", k: "僵尸 丧尸", c: "people-body" },
  { g: "💆", n: "person getting massage", k: "按摩 放松", c: "people-body" },
  { g: "💇", n: "person getting haircut", k: "理发 剪发", c: "people-body" },
  { g: "🚶", n: "person walking", k: "走路 步行", c: "people-body" },
  { g: "🧍", n: "person standing", k: "站立 人", c: "people-body" },
  { g: "🧎", n: "person kneeling", k: "跪 祈祷", c: "people-body" },
  { g: "🏃", n: "person running", k: "跑步 奔跑 运动", c: "people-body" },
  { g: "💃", n: "woman dancing", k: "跳舞 舞蹈", c: "people-body" },
  { g: "🕺", n: "man dancing", k: "跳舞 舞蹈", c: "people-body" },
  { g: "🕴", n: "person in suit levitating", k: "西装 悬浮", c: "people-body" },
  { g: "👯", n: "people with bunny ears", k: "兔子耳朵 派对", c: "people-body" },
  { g: "🧖", n: "person in steamy room", k: "桑拿 汗蒸", c: "people-body" },
  { g: "🧗", n: "person climbing", k: "攀爬 登山", c: "people-body" },
  { g: "🤺", n: "person fencing", k: "击剑 运动", c: "people-body" },
  { g: "🏇", n: "horse racing", k: "赛马 骑手", c: "people-body" },
  { g: "⛷", n: "skier", k: "滑雪 冬季", c: "people-body" },
  { g: "🏂", n: "snowboarder", k: "单板滑雪 冬季", c: "people-body" },
  { g: "🏌", n: "golfer", k: "高尔夫 运动", c: "people-body" },
  { g: "🏄", n: "person surfing", k: "冲浪 运动", c: "people-body" },
  { g: "🚣", n: "person rowing boat", k: "划船 运动", c: "people-body" },
  { g: "🛀", n: "person taking bath", k: "洗澡 沐浴", c: "people-body" },
  { g: "🛌", n: "person in bed", k: "睡觉 床上 休息", c: "people-body" },
  { g: "👫", n: "woman and man holding hands", k: "牵手 情侣", c: "people-body" },
  { g: "👬", n: "two men holding hands", k: "牵手 情侣", c: "people-body" },
  { g: "👭", n: "two women holding hands", k: "牵手 情侣", c: "people-body" },
  { g: "💏", n: "kiss", k: "亲吻 情侣", c: "people-body" },
  { g: "💑", n: "couple with heart", k: "情侣 爱心", c: "people-body" },
  { g: "👪", n: "family", k: "家庭 家人", c: "people-body" },
  { g: "🗣", n: "speaking head silhouette", k: "说话 侧影", c: "people-body" },
  { g: "🐶", n: "dog face", k: "狗 狗狗 宠物", c: "animals-nature" },
  { g: "🐕", n: "dog", k: "狗 狗狗 宠物", c: "animals-nature" },
  { g: "🐩", n: "poodle", k: "贵宾犬 狗 宠物", c: "animals-nature" },
  { g: "🐺", n: "wolf", k: "狼 野性", c: "animals-nature" },
  { g: "🦊", n: "fox", k: "狐狸 狡猾", c: "animals-nature" },
  { g: "🦝", n: "raccoon", k: "浣熊 动物", c: "animals-nature" },
  { g: "🐱", n: "cat face", k: "猫 猫咪 宠物", c: "animals-nature" },
  { g: "🐈", n: "cat", k: "猫 猫咪 宠物", c: "animals-nature" },
  { g: "🦁", n: "lion", k: "狮子 王者", c: "animals-nature" },
  { g: "🐯", n: "tiger face", k: "老虎 虎", c: "animals-nature" },
  { g: "🐅", n: "tiger", k: "老虎 虎", c: "animals-nature" },
  { g: "🐆", n: "leopard", k: "豹 猎豹", c: "animals-nature" },
  { g: "🐴", n: "horse face", k: "马 骏马", c: "animals-nature" },
  { g: "🐎", n: "horse", k: "马 骑马", c: "animals-nature" },
  { g: "🦄", n: "unicorn", k: "独角兽 神话", c: "animals-nature" },
  { g: "🦓", n: "zebra", k: "斑马 动物", c: "animals-nature" },
  { g: "🦌", n: "deer", k: "鹿 动物", c: "animals-nature" },
  { g: "🦬", n: "bison", k: "野牛 动物", c: "animals-nature" },
  { g: "🐮", n: "cow face", k: "牛 奶牛", c: "animals-nature" },
  { g: "🐂", n: "ox", k: "公牛 牛", c: "animals-nature" },
  { g: "🐃", n: "water buffalo", k: "水牛 牛", c: "animals-nature" },
  { g: "🐄", n: "cow", k: "牛 奶牛", c: "animals-nature" },
  { g: "🐷", n: "pig face", k: "猪 小猪", c: "animals-nature" },
  { g: "🐖", n: "pig", k: "猪 小猪", c: "animals-nature" },
  { g: "🐗", n: "boar", k: "野猪 猪", c: "animals-nature" },
  { g: "🐽", n: "pig nose", k: "猪鼻子 猪", c: "animals-nature" },
  { g: "🐏", n: "ram", k: "公羊 羊", c: "animals-nature" },
  { g: "🐑", n: "sheep", k: "绵羊 羊", c: "animals-nature" },
  { g: "🐐", n: "goat", k: "山羊 羊", c: "animals-nature" },
  { g: "🐪", n: "camel", k: "骆驼 沙漠", c: "animals-nature" },
  { g: "🐫", n: "two-hump camel", k: "骆驼 沙漠", c: "animals-nature" },
  { g: "🦙", n: "llama", k: "羊驼 骆驼", c: "animals-nature" },
  { g: "🦒", n: "giraffe", k: "长颈鹿 动物", c: "animals-nature" },
  { g: "🐘", n: "elephant", k: "大象 动物", c: "animals-nature" },
  { g: "🦣", n: "mammoth", k: "猛犸象 史前", c: "animals-nature" },
  { g: "🦏", n: "rhinoceros", k: "犀牛 动物", c: "animals-nature" },
  { g: "🦛", n: "hippopotamus", k: "河马 动物", c: "animals-nature" },
  { g: "🐭", n: "mouse face", k: "老鼠 耗子", c: "animals-nature" },
  { g: "🐁", n: "mouse", k: "老鼠 耗子", c: "animals-nature" },
  { g: "🐀", n: "rat", k: "老鼠 耗子", c: "animals-nature" },
  { g: "🐹", n: "hamster", k: "仓鼠 宠物", c: "animals-nature" },
  { g: "🐰", n: "rabbit face", k: "兔子 兔", c: "animals-nature" },
  { g: "🐇", n: "rabbit", k: "兔子 兔", c: "animals-nature" },
  { g: "🐿", n: "chipmunk", k: "花栗鼠 松鼠", c: "animals-nature" },
  { g: "🦫", n: "beaver", k: "河狸 动物", c: "animals-nature" },
  { g: "🦔", n: "hedgehog", k: "刺猬 动物", c: "animals-nature" },
  { g: "🦇", n: "bat", k: "蝙蝠 夜晚", c: "animals-nature" },
  { g: "🐻", n: "bear", k: "熊 动物", c: "animals-nature" },
  { g: "🐼", n: "panda", k: "熊猫 国宝", c: "animals-nature" },
  { g: "🦥", n: "sloth", k: "树懒 慢", c: "animals-nature" },
  { g: "🦦", n: "otter", k: "水獭 动物", c: "animals-nature" },
  { g: "🦨", n: "skunk", k: "臭鼬 动物", c: "animals-nature" },
  { g: "🦘", n: "kangaroo", k: "袋鼠 动物", c: "animals-nature" },
  { g: "🦡", n: "badger", k: "獾 动物", c: "animals-nature" },
  { g: "🐾", n: "paw prints", k: "爪印 脚印 宠物", c: "animals-nature" },
  { g: "🦃", n: "turkey", k: "火鸡 感恩节", c: "animals-nature" },
  { g: "🐔", n: "chicken", k: "鸡 小鸡", c: "animals-nature" },
  { g: "🐓", n: "rooster", k: "公鸡 鸡", c: "animals-nature" },
  { g: "🐣", n: "hatching chick", k: "小鸡 破壳", c: "animals-nature" },
  { g: "🐤", n: "baby chick", k: "小鸡 幼鸟", c: "animals-nature" },
  { g: "🐥", n: "front-facing baby chick", k: "小鸡 正面", c: "animals-nature" },
  { g: "🐦", n: "bird", k: "鸟 小鸟", c: "animals-nature" },
  { g: "🐧", n: "penguin", k: "企鹅 南极", c: "animals-nature" },
  { g: "🕊", n: "dove", k: "鸽子 和平", c: "animals-nature" },
  { g: "🦅", n: "eagle", k: "老鹰 鹰", c: "animals-nature" },
  { g: "🦆", n: "duck", k: "鸭子 鸭", c: "animals-nature" },
  { g: "🦢", n: "swan", k: "天鹅 优雅", c: "animals-nature" },
  { g: "🦉", n: "owl", k: "猫头鹰 智慧", c: "animals-nature" },
  { g: "🦤", n: "dodo", k: "渡渡鸟 灭绝", c: "animals-nature" },
  { g: "🪶", n: "feather", k: "羽毛 轻", c: "animals-nature" },
  { g: "🦩", n: "flamingo", k: "火烈鸟 粉色", c: "animals-nature" },
  { g: "🦚", n: "peacock", k: "孔雀 华丽", c: "animals-nature" },
  { g: "🦜", n: "parrot", k: "鹦鹉 学舌", c: "animals-nature" },
  { g: "🐸", n: "frog", k: "青蛙 蛙", c: "animals-nature" },
  { g: "🐊", n: "crocodile", k: "鳄鱼 爬行", c: "animals-nature" },
  { g: "🐢", n: "turtle", k: "乌龟 龟", c: "animals-nature" },
  { g: "🦎", n: "lizard", k: "蜥蜴 爬行", c: "animals-nature" },
  { g: "🐍", n: "snake", k: "蛇 爬行", c: "animals-nature" },
  { g: "🐲", n: "dragon face", k: "龙 龙头", c: "animals-nature" },
  { g: "🐉", n: "dragon", k: "龙 神话", c: "animals-nature" },
  { g: "🦕", n: "sauropod", k: "恐龙 长颈龙", c: "animals-nature" },
  { g: "🦖", n: "T-Rex", k: "恐龙 霸王龙", c: "animals-nature" },
  { g: "🐳", n: "spouting whale", k: "鲸鱼 喷水", c: "animals-nature" },
  { g: "🐋", n: "whale", k: "鲸鱼 大海", c: "animals-nature" },
  { g: "🐬", n: "dolphin", k: "海豚 大海", c: "animals-nature" },
  { g: "🐟", n: "fish", k: "鱼 小鱼", c: "animals-nature" },
  { g: "🐠", n: "tropical fish", k: "热带鱼 鱼", c: "animals-nature" },
  { g: "🐡", n: "blowfish", k: "河豚 鱼", c: "animals-nature" },
  { g: "🦈", n: "shark", k: "鲨鱼 危险", c: "animals-nature" },
  { g: "🐙", n: "octopus", k: "章鱼 触手", c: "animals-nature" },
  { g: "🐚", n: "spiral shell", k: "贝壳 海螺", c: "animals-nature" },
  { g: "🪸", n: "coral", k: "珊瑚 海洋", c: "animals-nature" },
  { g: "🐌", n: "snail", k: "蜗牛 慢", c: "animals-nature" },
  { g: "🦋", n: "butterfly", k: "蝴蝶 美丽", c: "animals-nature" },
  { g: "🐛", n: "bug", k: "虫子 昆虫", c: "animals-nature" },
  { g: "🐜", n: "ant", k: "蚂蚁 昆虫", c: "animals-nature" },
  { g: "🐝", n: "honeybee", k: "蜜蜂 蜂蜜", c: "animals-nature" },
  { g: "🪲", n: "beetle", k: "甲虫 昆虫", c: "animals-nature" },
  { g: "🐞", n: "lady beetle", k: "瓢虫 昆虫", c: "animals-nature" },
  { g: "🦗", n: "cricket", k: "蟋蟀 昆虫", c: "animals-nature" },
  { g: "🪳", n: "cockroach", k: "蟑螂 害虫", c: "animals-nature" },
  { g: "🕷", n: "spider", k: "蜘蛛 网", c: "animals-nature" },
  { g: "🕸", n: "spider web", k: "蜘蛛网 网", c: "animals-nature" },
  { g: "🦂", n: "scorpion", k: "蝎子 毒", c: "animals-nature" },
  { g: "🦟", n: "mosquito", k: "蚊子 叮", c: "animals-nature" },
  { g: "🪰", n: "fly", k: "苍蝇 昆虫", c: "animals-nature" },
  { g: "🪱", n: "worm", k: "蠕虫 虫", c: "animals-nature" },
  { g: "🦠", n: "microbe", k: "微生物 病毒 细菌", c: "animals-nature" },
  { g: "💐", n: "bouquet", k: "花束 鲜花 礼物", c: "animals-nature" },
  { g: "🌸", n: "cherry blossom", k: "樱花 春天", c: "animals-nature" },
  { g: "💮", n: "white flower", k: "白花 花", c: "animals-nature" },
  { g: "🏵", n: "rosette", k: "花结 奖章", c: "animals-nature" },
  { g: "🌹", n: "rose", k: "玫瑰 爱情 花", c: "animals-nature" },
  { g: "🥀", n: "wilted flower", k: "枯萎 花 凋谢", c: "animals-nature" },
  { g: "🌺", n: "hibiscus", k: "木槿 花 热带", c: "animals-nature" },
  { g: "🌻", n: "sunflower", k: "向日葵 花 阳光", c: "animals-nature" },
  { g: "🌼", n: "blossom", k: "花朵 花", c: "animals-nature" },
  { g: "🌷", n: "tulip", k: "郁金香 花", c: "animals-nature" },
  { g: "🌱", n: "seedling", k: "幼苗 发芽 生长", c: "animals-nature" },
  { g: "🪴", n: "potted plant", k: "盆栽 植物", c: "animals-nature" },
  { g: "🌲", n: "evergreen tree", k: "常青树 树", c: "animals-nature" },
  { g: "🌳", n: "deciduous tree", k: "落叶树 树", c: "animals-nature" },
  { g: "🌴", n: "palm tree", k: "棕榈树 海滩", c: "animals-nature" },
  { g: "🌵", n: "cactus", k: "仙人掌 沙漠", c: "animals-nature" },
  { g: "🌾", n: "sheaf of rice", k: "稻穗 收获", c: "animals-nature" },
  { g: "🌿", n: "herb", k: "草药 植物", c: "animals-nature" },
  { g: "☘", n: "shamrock", k: "三叶草 幸运", c: "animals-nature" },
  { g: "🍀", n: "four leaf clover", k: "四叶草 幸运", c: "animals-nature" },
  { g: "🍁", n: "maple leaf", k: "枫叶 秋天", c: "animals-nature" },
  { g: "🍂", n: "fallen leaf", k: "落叶 秋天", c: "animals-nature" },
  { g: "🍃", n: "leaf fluttering in wind", k: "风吹叶 秋天", c: "animals-nature" },
  { g: "🪹", n: "empty nest", k: "空巢 鸟巢", c: "animals-nature" },
  { g: "🪺", n: "nest with eggs", k: "鸟巢 蛋", c: "animals-nature" },
  { g: "🍄", n: "mushroom", k: "蘑菇 菌", c: "animals-nature" },
  { g: "🪷", n: "lotus", k: "莲花 荷花", c: "animals-nature" },
  { g: "🌍", n: "globe showing Europe-Africa", k: "地球 世界", c: "animals-nature" },
  { g: "🌎", n: "globe showing Americas", k: "地球 美洲", c: "animals-nature" },
  { g: "🌏", n: "globe showing Asia-Australia", k: "地球 亚洲", c: "animals-nature" },
  { g: "🌐", n: "globe with meridians", k: "地球 经线", c: "animals-nature" },
  { g: "🗺", n: "world map", k: "世界地图 地图", c: "animals-nature" },
  { g: "🗻", n: "mount fuji", k: "富士山 山", c: "animals-nature" },
  { g: "🌋", n: "volcano", k: "火山 喷发", c: "animals-nature" },
  { g: "🗾", n: "map of Japan", k: "日本地图 地图", c: "animals-nature" },
  { g: "🏔", n: "snow-capped mountain", k: "雪山 山", c: "animals-nature" },
  { g: "⛰", n: "mountain", k: "山 登山", c: "animals-nature" },
  { g: "🌌", n: "milky way", k: "银河 星空", c: "animals-nature" },
  { g: "🌊", n: "water wave", k: "海浪 水 波浪", c: "animals-nature" },
  { g: "🌁", n: "foggy", k: "雾 模糊 桥", c: "animals-nature" },
  { g: "🌃", n: "night with stars", k: "夜晚 星星", c: "animals-nature" },
  { g: "🏙", n: "cityscape", k: "城市 建筑", c: "animals-nature" },
  { g: "🌄", n: "sunrise over mountains", k: "日出 山", c: "animals-nature" },
  { g: "🌅", n: "sunrise", k: "日出 早晨", c: "animals-nature" },
  { g: "🌆", n: "cityscape at dusk", k: "黄昏 城市", c: "animals-nature" },
  { g: "🌇", n: "sunset", k: "日落 傍晚", c: "animals-nature" },
  { g: "🌉", n: "bridge at night", k: "夜桥 夜晚 夜景", c: "animals-nature" },
  { g: "☀", n: "sun", k: "太阳 晴天", c: "animals-nature" },
  { g: "🌝", n: "full moon face", k: "满月 月亮", c: "animals-nature" },
  { g: "🌚", n: "new moon face", k: "新月 月亮", c: "animals-nature" },
  { g: "🌑", n: "new moon", k: "月亮 新月", c: "animals-nature" },
  { g: "🌞", n: "sun with face", k: "太阳 晴天", c: "animals-nature" },
  { g: "⭐", n: "star", k: "星星 收藏 好评", c: "animals-nature" },
  { g: "🌟", n: "glowing star", k: "闪耀 星星", c: "animals-nature" },
  { g: "🌠", n: "shooting star", k: "流星 许愿", c: "animals-nature" },
  { g: "☁", n: "cloud", k: "云 多云", c: "animals-nature" },
  { g: "⛅", n: "sun behind cloud", k: "多云 晴间多云", c: "animals-nature" },
  { g: "⛈", n: "cloud with lightning and rain", k: "雷阵雨 天气", c: "animals-nature" },
  { g: "🌤", n: "sun behind small cloud", k: "多云 天气", c: "animals-nature" },
  { g: "🌥", n: "sun behind large cloud", k: "阴天 天气", c: "animals-nature" },
  { g: "🌦", n: "sun behind rain cloud", k: "阵雨 天气", c: "animals-nature" },
  { g: "🌧", n: "cloud with rain", k: "下雨 雨", c: "animals-nature" },
  { g: "🌨", n: "cloud with snow", k: "下雪 雪", c: "animals-nature" },
  { g: "🌩", n: "cloud with lightning", k: "闪电 雷", c: "animals-nature" },
  { g: "🌪", n: "tornado", k: "龙卷风 天气", c: "animals-nature" },
  { g: "🌫", n: "fog", k: "雾 天气", c: "animals-nature" },
  { g: "🌬", n: "wind face", k: "风 天气", c: "animals-nature" },
  { g: "🌈", n: "rainbow", k: "彩虹 好运", c: "animals-nature" },
  { g: "🌂", n: "closed umbrella", k: "雨伞 关闭", c: "animals-nature" },
  { g: "☂", n: "umbrella", k: "雨伞 下雨", c: "animals-nature" },
  { g: "⚡", n: "high voltage", k: "闪电 高压 电", c: "animals-nature" },
  { g: "❄", n: "snowflake", k: "雪花 冬天", c: "animals-nature" },
  { g: "💧", n: "droplet", k: "水滴 水", c: "animals-nature" },
  { g: "🔥", n: "fire", k: "火 火焰 热门 燃烧", c: "animals-nature" },
  { g: "🍏", n: "green apple", k: "青苹果 苹果 水果", c: "food-drink" },
  { g: "🍎", n: "red apple", k: "苹果 水果", c: "food-drink" },
  { g: "🍐", n: "pear", k: "梨 水果", c: "food-drink" },
  { g: "🍊", n: "tangerine", k: "橘子 柑橘 水果", c: "food-drink" },
  { g: "🍋", n: "lemon", k: "柠檬 水果 酸", c: "food-drink" },
  { g: "🍌", n: "banana", k: "香蕉 水果", c: "food-drink" },
  { g: "🍉", n: "watermelon", k: "西瓜 水果", c: "food-drink" },
  { g: "🍇", n: "grapes", k: "葡萄 水果", c: "food-drink" },
  { g: "🍓", n: "strawberry", k: "草莓 水果", c: "food-drink" },
  { g: "🫐", n: "blueberries", k: "蓝莓 水果", c: "food-drink" },
  { g: "🍈", n: "melon", k: "甜瓜 水果", c: "food-drink" },
  { g: "🍒", n: "cherries", k: "樱桃 水果", c: "food-drink" },
  { g: "🍑", n: "peach", k: "桃子 水果", c: "food-drink" },
  { g: "🥭", n: "mango", k: "芒果 水果", c: "food-drink" },
  { g: "🍍", n: "pineapple", k: "菠萝 水果", c: "food-drink" },
  { g: "🥥", n: "coconut", k: "椰子 热带", c: "food-drink" },
  { g: "🥝", n: "kiwi fruit", k: "猕猴桃 奇异果", c: "food-drink" },
  { g: "🍅", n: "tomato", k: "西红柿 番茄 蔬菜", c: "food-drink" },
  { g: "🫒", n: "olive", k: "橄榄 地中海", c: "food-drink" },
  { g: "🍆", n: "eggplant", k: "茄子 蔬菜", c: "food-drink" },
  { g: "🥑", n: "avocado", k: "牛油果 鳄梨", c: "food-drink" },
  { g: "🫑", n: "bell pepper", k: "甜椒 蔬菜", c: "food-drink" },
  { g: "🥒", n: "cucumber", k: "黄瓜 蔬菜", c: "food-drink" },
  { g: "🥬", n: "leafy green", k: "绿叶菜 蔬菜", c: "food-drink" },
  { g: "🥦", n: "broccoli", k: "西兰花 蔬菜", c: "food-drink" },
  { g: "🧄", n: "garlic", k: "大蒜 蒜", c: "food-drink" },
  { g: "🧅", n: "onion", k: "洋葱 蔬菜", c: "food-drink" },
  { g: "🥕", n: "carrot", k: "胡萝卜 蔬菜", c: "food-drink" },
  { g: "🫔", n: "tamale", k: "玉米粽 食物", c: "food-drink" },
  { g: "🥔", n: "potato", k: "土豆 马铃薯", c: "food-drink" },
  { g: "🍠", n: "roasted sweet potato", k: "烤红薯 地瓜", c: "food-drink" },
  { g: "🥐", n: "croissant", k: "牛角包 面包", c: "food-drink" },
  { g: "🥯", n: "bagel", k: "贝果 面包", c: "food-drink" },
  { g: "🍞", n: "bread", k: "面包 吐司", c: "food-drink" },
  { g: "🥖", n: "baguette bread", k: "法棍 面包", c: "food-drink" },
  { g: "🫓", n: "flatbread", k: "扁面包 饼", c: "food-drink" },
  { g: "🥨", n: "pretzel", k: "椒盐卷饼 面包", c: "food-drink" },
  { g: "🧀", n: "cheese wedge", k: "奶酪 芝士", c: "food-drink" },
  { g: "🥚", n: "egg", k: "鸡蛋 蛋", c: "food-drink" },
  { g: "🍳", n: "cooking", k: "煎蛋 烹饪", c: "food-drink" },
  { g: "🧈", n: "butter", k: "黄油 奶油", c: "food-drink" },
  { g: "🥞", n: "pancakes", k: "煎饼 松饼", c: "food-drink" },
  { g: "🧇", n: "waffle", k: "华夫饼 早餐", c: "food-drink" },
  { g: "🥓", n: "bacon", k: "培根 肉", c: "food-drink" },
  { g: "🥩", n: "cut of meat", k: "肉 牛排", c: "food-drink" },
  { g: "🍗", n: "poultry leg", k: "鸡腿 肉", c: "food-drink" },
  { g: "🍖", n: "meat on bone", k: "骨头肉 肉", c: "food-drink" },
  { g: "🌭", n: "hot dog", k: "热狗 快餐", c: "food-drink" },
  { g: "🍔", n: "hamburger", k: "汉堡 快餐", c: "food-drink" },
  { g: "🍟", n: "french fries", k: "薯条 快餐", c: "food-drink" },
  { g: "🍕", n: "pizza", k: "披萨 比萨", c: "food-drink" },
  { g: "🥪", n: "sandwich", k: "三明治 快餐", c: "food-drink" },
  { g: "🌮", n: "taco", k: "墨西哥卷 快餐", c: "food-drink" },
  { g: "🌯", n: "burrito", k: "墨西哥卷饼 快餐", c: "food-drink" },
  { g: "🫕", n: "fondue", k: "芝士火锅 火锅", c: "food-drink" },
  { g: "🥙", n: " stuffed flatbread", k: "馅饼 食物", c: "food-drink" },
  { g: "🧆", n: "dumpling", k: "饺子 水饺", c: "food-drink" },
  { g: "🥟", n: "dumpling", k: "饺子 汤圆", c: "food-drink" },
  { g: "🥢", n: "chopsticks", k: "筷子 餐具", c: "food-drink" },
  { g: "🍜", n: "steaming bowl", k: "拉面 面条 热汤", c: "food-drink" },
  { g: "🍝", n: "spaghetti", k: "意大利面 面条 意面", c: "food-drink" },
  { g: "🍛", n: "curry rice", k: "咖喱饭 米饭", c: "food-drink" },
  { g: "🍣", n: "sushi", k: "寿司 日本料理", c: "food-drink" },
  { g: "🍤", n: "fried shrimp", k: "炸虾 海鲜", c: "food-drink" },
  { g: "🍥", n: "fish cake with swirl", k: "鱼板 关东煮", c: "food-drink" },
  { g: "🥮", n: "moon cake", k: "月饼 中秋", c: "food-drink" },
  { g: "🍡", n: "dango", k: "团子 日本", c: "food-drink" },
  { g: "🥘", n: "shallow pan of food", k: "平底锅 炖菜", c: "food-drink" },
  { g: "🥗", n: "green salad", k: "沙拉 蔬菜", c: "food-drink" },
  { g: "🍿", n: "popcorn", k: "爆米花 电影", c: "food-drink" },
  { g: "🧂", n: "salt", k: "盐 调味", c: "food-drink" },
  { g: "🥫", n: "canned food", k: "罐头 食物", c: "food-drink" },
  { g: "🍱", n: "bento box", k: "便当 饭盒", c: "food-drink" },
  { g: "🍘", n: "rice cracker", k: "米饼 仙贝", c: "food-drink" },
  { g: "🍙", n: "rice ball", k: "饭团 日本", c: "food-drink" },
  { g: "🍚", n: "cooked rice", k: "米饭 白饭", c: "food-drink" },
  { g: "🍢", n: "oden", k: "关东煮", c: "food-drink" },
  { g: "🍦", n: "soft ice cream", k: "冰淇淋 甜筒", c: "food-drink" },
  { g: "🍧", n: "shaved ice", k: "刨冰 甜点", c: "food-drink" },
  { g: "🍨", n: "ice cream", k: "冰淇淋 甜点", c: "food-drink" },
  { g: "🍩", n: "doughnut", k: "甜甜圈 甜点", c: "food-drink" },
  { g: "🍪", n: "cookie", k: "曲奇 饼干", c: "food-drink" },
  { g: "🎂", n: "birthday cake", k: "生日蛋糕 庆祝", c: "food-drink" },
  { g: "🍰", n: "shortcake", k: "蛋糕 草莓蛋糕", c: "food-drink" },
  { g: "🧁", n: "cupcake", k: "纸杯蛋糕 甜点", c: "food-drink" },
  { g: "🥧", n: "pie", k: "派 馅饼", c: "food-drink" },
  { g: "🍫", n: "chocolate bar", k: "巧克力 甜食", c: "food-drink" },
  { g: "🍬", n: "candy", k: "糖果 甜食", c: "food-drink" },
  { g: "🍭", n: "lollipop", k: "棒棒糖 糖果", c: "food-drink" },
  { g: "🍮", n: "custard", k: "布丁 蛋奶", c: "food-drink" },
  { g: "🍯", n: "honey pot", k: "蜂蜜 甜", c: "food-drink" },
  { g: "🍼", n: "baby bottle", k: "奶瓶 婴儿", c: "food-drink" },
  { g: "🥛", n: "glass of milk", k: "牛奶 饮品", c: "food-drink" },
  { g: "☕", n: "hot beverage", k: "咖啡 热饮 茶", c: "food-drink" },
  { g: "🫖", n: "teapot", k: "茶壶 茶", c: "food-drink" },
  { g: "🍵", n: "teacup without handle", k: "茶杯 茶", c: "food-drink" },
  { g: "🍶", n: "sake", k: "清酒 日本酒", c: "food-drink" },
  { g: "🍾", n: "bottle with popping cork", k: "香槟 庆祝", c: "food-drink" },
  { g: "🍷", n: "wine glass", k: "红酒 酒杯", c: "food-drink" },
  { g: "🍸", n: "cocktail glass", k: "鸡尾酒 酒吧", c: "food-drink" },
  { g: "🍹", n: "tropical drink", k: "热带饮料 果汁", c: "food-drink" },
  { g: "🍺", n: "beer mug", k: "啤酒 干杯", c: "food-drink" },
  { g: "🍻", n: "clinking beer mugs", k: "干杯 啤酒", c: "food-drink" },
  { g: "🥂", n: "clinking glasses", k: "碰杯 庆祝", c: "food-drink" },
  { g: "🥃", n: "tumbler glass", k: "威士忌 酒杯", c: "food-drink" },
  { g: "🥤", n: "cup with straw", k: "饮料 吸管", c: "food-drink" },
  { g: "🧋", n: "bubble tea", k: "奶茶 珍珠奶茶", c: "food-drink" },
  { g: "🧃", n: "beverage box", k: "盒装饮料 果汁", c: "food-drink" },
  { g: "🧉", n: "mate", k: "马黛茶 茶", c: "food-drink" },
  { g: "🧊", n: "ice", k: "冰块 冰", c: "food-drink" },
  { g: "🍴", n: "fork and knife", k: "餐具 吃饭", c: "food-drink" },
  { g: "🥄", n: "spoon", k: "勺子 餐具", c: "food-drink" },
  { g: "🔪", n: "kitchen knife", k: "菜刀 刀", c: "food-drink" },
  { g: "🏺", n: "amphora", k: "陶罐 古董", c: "food-drink" },
  { g: "🚗", n: "automobile", k: "汽车 轿车", c: "travel-places" },
  { g: "🚕", n: "taxi", k: "出租车 打车", c: "travel-places" },
  { g: "🚙", n: "sport utility vehicle", k: "越野车 SUV", c: "travel-places" },
  { g: "🚌", n: "bus", k: "公交车 巴士", c: "travel-places" },
  { g: "🚎", n: "trolleybus", k: "无轨电车 公交", c: "travel-places" },
  { g: "🏎", n: "racing car", k: "赛车 跑车", c: "travel-places" },
  { g: "🚓", n: "police car", k: "警车 警察", c: "travel-places" },
  { g: "🚑", n: "ambulance", k: "救护车 急救", c: "travel-places" },
  { g: "🚒", n: "fire engine", k: "消防车 救火", c: "travel-places" },
  { g: "🚐", n: "minibus", k: "小巴 面包车", c: "travel-places" },
  { g: "🚚", n: "delivery truck", k: "货车 卡车", c: "travel-places" },
  { g: "🚛", n: "articulated lorry", k: "卡车 货车", c: "travel-places" },
  { g: "🚜", n: "tractor", k: "拖拉机 农业", c: "travel-places" },
  { g: "🏱", n: "racing car", k: "赛车", c: "travel-places" },
  { g: "🛵", n: "motor scooter", k: "踏板车 摩托", c: "travel-places" },
  { g: "🏍", n: "motorcycle", k: "摩托车 机车 摩托", c: "travel-places" },
  { g: "🚲", n: "bicycle", k: "自行车 单车 骑行", c: "travel-places" },
  { g: "🛴", n: "kick scooter", k: "滑板车 电动", c: "travel-places" },
  { g: "🛹", n: "skateboard", k: "滑板 运动", c: "travel-places" },
  { g: "🚏", n: "bus stop", k: "公交站 车站", c: "travel-places" },
  { g: "🛣", n: "motorway", k: "高速公路 公路", c: "travel-places" },
  { g: "🛤", n: "railway track", k: "铁轨 铁路", c: "travel-places" },
  { g: "🚢", n: "ship", k: "轮船 船", c: "travel-places" },
  { g: "⛵", n: "sailboat", k: "帆船 船", c: "travel-places" },
  { g: "🚤", n: "speedboat", k: "快艇 船", c: "travel-places" },
  { g: "🛳", n: "passenger ship", k: "客船 邮轮", c: "travel-places" },
  { g: "⛴", n: "ferry", k: "渡轮 船", c: "travel-places" },
  { g: "🛥", n: "motor boat", k: "摩托艇 船", c: "travel-places" },
  { g: "🚥", n: "horizontal traffic light", k: "红绿灯 交通", c: "travel-places" },
  { g: "🚦", n: "vertical traffic light", k: "红绿灯 交通", c: "travel-places" },
  { g: "🚧", n: "construction", k: "施工 道路施工", c: "travel-places" },
  { g: "🚨", n: "police car light", k: "警灯 警报", c: "travel-places" },
  { g: "🚩", n: "triangular flag", k: "三角旗 旗帜", c: "travel-places" },
  { g: "🚪", n: "door", k: "门 入口", c: "travel-places" },
  { g: "🚫", n: "no entry", k: "禁止进入 禁止", c: "travel-places" },
  { g: "🚬", n: "cigarette", k: "香烟 吸烟", c: "travel-places" },
  { g: "🚭", n: "no smoking", k: "禁止吸烟", c: "travel-places" },
  { g: "🚯", n: "no littering", k: "禁止乱扔 垃圾", c: "travel-places" },
  { g: "🚰", n: "potable water", k: "饮用水 水", c: "travel-places" },
  { g: "🚱", n: "non-potable water", k: "非饮用水 水", c: "travel-places" },
  { g: "🚳", n: "no bicycles", k: "禁止自行车", c: "travel-places" },
  { g: "🚷", n: "no pedestrians", k: "禁止行人", c: "travel-places" },
  { g: "🚸", n: "children crossing", k: "儿童过街 注意 儿童", c: "travel-places" },
  { g: "🚹", n: "men's room", k: "男厕 洗手间", c: "travel-places" },
  { g: "🚺", n: "women's room", k: "女厕 洗手间", c: "travel-places" },
  { g: "🚻", n: "restroom", k: "洗手间 厕所", c: "travel-places" },
  { g: "🚼", n: "baby symbol", k: "婴儿 标识", c: "travel-places" },
  { g: "🚾", n: "water closet", k: "厕所 WC", c: "travel-places" },
  { g: "🛂", n: "passport control", k: "护照检查 出入境", c: "travel-places" },
  { g: "🛃", n: "customs", k: "海关 检查", c: "travel-places" },
  { g: "🛄", n: "baggage claim", k: "行李提取 机场", c: "travel-places" },
  { g: "🛅", n: "left luggage", k: "行李寄存 寄存", c: "travel-places" },
  { g: "⚠", n: "warning", k: "警告 注意 危险", c: "travel-places" },
  { g: "🏠", n: "house", k: "房子 家", c: "travel-places" },
  { g: "🏡", n: "house with garden", k: "花园住宅 家", c: "travel-places" },
  { g: "🏢", n: "office building", k: "办公楼 公司", c: "travel-places" },
  { g: "🏣", n: "Japanese post office", k: "邮局 日本", c: "travel-places" },
  { g: "🏤", n: "post office", k: "邮局 邮政", c: "travel-places" },
  { g: "🏥", n: "hospital", k: "医院 医疗", c: "travel-places" },
  { g: "🏦", n: "bank", k: "银行 金融", c: "travel-places" },
  { g: "🏨", n: "hotel", k: "酒店 住宿", c: "travel-places" },
  { g: "🏩", n: "love hotel", k: "情侣酒店 住宿", c: "travel-places" },
  { g: "🏪", n: "convenience store", k: "便利店 商店", c: "travel-places" },
  { g: "🏫", n: "school", k: "学校 教育", c: "travel-places" },
  { g: "🏬", n: "department store", k: "百货商店 购物", c: "travel-places" },
  { g: "🏭", n: "factory", k: "工厂 制造", c: "travel-places" },
  { g: "🏯", n: "Japanese castle", k: "城堡 日本", c: "travel-places" },
  { g: "🏰", n: "castle", k: "城堡 宫殿", c: "travel-places" },
  { g: "💒", n: "wedding", k: "婚礼 结婚", c: "travel-places" },
  { g: "🗼", n: "Tokyo tower", k: "东京塔 地标", c: "travel-places" },
  { g: "🗽", n: "Statue of Liberty", k: "自由女神像 地标", c: "travel-places" },
  { g: "⛪", n: "church", k: "教堂 宗教", c: "travel-places" },
  { g: "🕌", n: "mosque", k: "清真寺 宗教", c: "travel-places" },
  { g: "🕍", n: "synagogue", k: "犹太教堂 宗教", c: "travel-places" },
  { g: "⛩", n: "shinto shrine", k: "神社 日本", c: "travel-places" },
  { g: "🕋", n: "kaaba", k: "天房 麦加", c: "travel-places" },
  { g: "⛲", n: "fountain", k: "喷泉 公园", c: "travel-places" },
  { g: "⛺", n: "tent", k: "帐篷 露营", c: "travel-places" },
  { g: "🏕", n: "camping", k: "露营 户外", c: "travel-places" },
  { g: "🏖", n: "beach with umbrella", k: "海滩 度假", c: "travel-places" },
  { g: "🏗", n: "building construction", k: "建筑施工 工地", c: "travel-places" },
  { g: "🏘", n: "houses", k: "房屋 住宅", c: "travel-places" },
  { g: "🏚", n: "derelict house", k: "废弃房屋 破旧 废墟 废弃", c: "travel-places" },
  { g: "🏜", n: "desert", k: "沙漠 沙", c: "travel-places" },
  { g: "🏝", n: "desert island", k: "荒岛 海岛", c: "travel-places" },
  { g: "🏞", n: "national park", k: "国家公园 自然", c: "travel-places" },
  { g: "🏟", n: "stadium", k: "体育场 比赛", c: "travel-places" },
  { g: "🏛", n: "classical building", k: "古典建筑 地标", c: "travel-places" },
  { g: "🎠", n: "carousel horse", k: "旋转木马 游乐", c: "travel-places" },
  { g: "🎡", n: "ferris wheel", k: "摩天轮 游乐场", c: "travel-places" },
  { g: "🎢", n: "roller coaster", k: "过山车 游乐场", c: "travel-places" },
  { g: "🎣", n: "fishing pole", k: "钓鱼 鱼竿", c: "travel-places" },
  { g: "🎤", n: "studio microphone", k: "麦克风 录音", c: "travel-places" },
  { g: "🎥", n: "movie camera", k: "摄影机 电影", c: "travel-places" },
  { g: "🎦", n: "cinema", k: "电影院 电影", c: "travel-places" },
  { g: "🎧", n: "headphone", k: "耳机 音乐", c: "travel-places" },
  { g: "🎨", n: "artist palette", k: "调色板 艺术 绘画", c: "travel-places" },
  { g: "🎩", n: "top hat", k: "礼帽 帽子", c: "travel-places" },
  { g: "🎪", n: "circus tent", k: "马戏团 帐篷", c: "travel-places" },
  { g: "🎫", n: "ticket", k: "门票 票", c: "travel-places" },
  { g: "🎬", n: "clapper board", k: "场记板 电影", c: "travel-places" },
  { g: "🎭", n: "performing arts", k: "表演 戏剧", c: "travel-places" },
  { g: "🎮", n: "video game", k: "电子游戏 手柄", c: "travel-places" },
  { g: "🎯", n: "direct hit", k: "正中靶心 目标 命中", c: "travel-places" },
  { g: "🎰", n: "slot machine", k: "老虎机 赌博", c: "travel-places" },
  { g: "🎱", n: "billiards", k: "台球 桌球", c: "travel-places" },
  { g: "🎲", n: "game die", k: "骰子 游戏", c: "travel-places" },
  { g: "🎳", n: "bowling", k: "保龄球 运动", c: "travel-places" },
  { g: "🎴", n: "flower playing cards", k: "花札 纸牌", c: "travel-places" },
  { g: "🎵", n: "musical note", k: "音符 音乐", c: "travel-places" },
  { g: "🎶", n: "musical notes", k: "音符 音乐", c: "travel-places" },
  { g: "🎷", n: "saxophone", k: "萨克斯 乐器", c: "travel-places" },
  { g: "🎸", n: "guitar", k: "吉他 乐器", c: "travel-places" },
  { g: "🎹", n: "musical keyboard", k: "电子琴 乐器", c: "travel-places" },
  { g: "🎺", n: "trumpet", k: "小号 乐器", c: "travel-places" },
  { g: "🎻", n: "violin", k: "小提琴 乐器", c: "travel-places" },
  { g: "🎼", n: "musical score", k: "乐谱 音乐", c: "travel-places" },
  { g: "🎽", n: "running shirt", k: "运动服 跑步", c: "travel-places" },
  { g: "🎾", n: "tennis", k: "网球 运动", c: "travel-places" },
  { g: "🎿", n: "skis", k: "滑雪板 冬季 滑雪", c: "travel-places" },
  { g: "🏀", n: "basketball", k: "篮球 运动", c: "travel-places" },
  { g: "🏁", n: "chequered flag", k: "格子旗 终点", c: "travel-places" },
  { g: "🏅", n: "person lifting weights", k: "举重 健身", c: "travel-places" },
  { g: "🏆", n: "trophy", k: "奖杯 冠军 胜利", c: "travel-places" },
  { g: "🏈", n: "american football", k: "橄榄球 运动", c: "travel-places" },
  { g: "🏉", n: "rugby football", k: "橄榄球 运动", c: "travel-places" },
  { g: "🏊", n: "person swimming", k: "游泳 泳池", c: "travel-places" },
  { g: "🏋", n: "person biking", k: "骑车 运动", c: "travel-places" },
  { g: "🏏", n: "cricket game", k: "板球 运动", c: "travel-places" },
  { g: "🏐", n: "volleyball", k: "排球 运动", c: "travel-places" },
  { g: "🏑", n: "field hockey", k: "曲棍球 运动", c: "travel-places" },
  { g: "🏒", n: "ice hockey", k: "冰球 运动", c: "travel-places" },
  { g: "🏓", n: "ping pong", k: "乒乓球 运动", c: "travel-places" },
  { g: "⚽", n: "soccer ball", k: "足球 运动", c: "travel-places" },
  { g: "⚾", n: "baseball", k: "棒球 运动", c: "travel-places" },
  { g: "🥎", n: "softball", k: "垒球 运动", c: "travel-places" },
  { g: "🥏", n: "flying disc", k: "飞盘 运动", c: "travel-places" },
  { g: "🥊", n: "boxing glove", k: "拳击手套 拳击", c: "travel-places" },
  { g: "🥋", n: "martial arts uniform", k: "武术 道服", c: "travel-places" },
  { g: "🥅", n: "goal net", k: "球门 进球", c: "travel-places" },
  { g: "⛳", n: "flag in hole", k: "高尔夫球洞 进洞 高尔夫", c: "travel-places" },
  { g: "⛸", n: "ice skate", k: "溜冰 冰鞋", c: "travel-places" },
  { g: "🛷", n: "sled", k: "雪橇 冬季", c: "travel-places" },
  { g: "🚀", n: "rocket", k: "火箭 发射 升空 launch spaceship", c: "travel-places" },
  { g: "🛸", n: "flying saucer", k: "飞碟 UFO", c: "travel-places" },
  { g: "🛺", n: "auto rickshaw", k: "三轮车 嘟嘟车", c: "travel-places" },
  { g: "🛻", n: "pickup truck", k: "皮卡 卡车", c: "travel-places" },
  { g: "🛼", n: "roller skate", k: "轮滑 旱冰", c: "travel-places" },
  { g: "🚮", n: "litter bin", k: "垃圾桶 垃圾", c: "travel-places" },
  { g: "🚴", n: "person mountain biking", k: "山地骑行", c: "travel-places" },
  { g: "🚵", n: "person mountain biking", k: "骑行", c: "travel-places" },
  { g: "🚿", n: "shower", k: "淋浴 洗澡", c: "travel-places" },
  { g: "🛁", n: "bathtub", k: "浴缸 泡澡", c: "travel-places" },
  { g: "⌚", n: "watch", k: "手表 时间", c: "objects" },
  { g: "📱", n: "mobile phone", k: "手机 电话", c: "objects" },
  { g: "📲", n: "mobile phone with arrow", k: "手机 接收", c: "objects" },
  { g: "☎", n: "telephone", k: "电话 座机", c: "objects" },
  { g: "📞", n: "telephone receiver", k: "电话 听筒", c: "objects" },
  { g: "📟", n: "pager", k: "传呼机 寻呼", c: "objects" },
  { g: "📠", n: "fax machine", k: "传真 办公", c: "objects" },
  { g: "🔋", n: "battery", k: "电池 电量", c: "objects" },
  { g: "🔌", n: "electric plug", k: "插头 电源", c: "objects" },
  { g: "💻", n: "laptop", k: "笔记本电脑 电脑", c: "objects" },
  { g: "🖥", n: "desktop computer", k: "台式电脑 显示器", c: "objects" },
  { g: "🖨", n: "printer", k: "打印机 办公", c: "objects" },
  { g: "⌨", n: "keyboard", k: "键盘 输入", c: "objects" },
  { g: "🖱", n: "computer mouse", k: "鼠标 电脑", c: "objects" },
  { g: "🖲", n: "trackball", k: "轨迹球 鼠标", c: "objects" },
  { g: "💽", n: "computer disk", k: "光盘 存储", c: "objects" },
  { g: "💾", n: "floppy disk", k: "软盘 存储", c: "objects" },
  { g: "💿", n: "optical disk", k: "光盘 CD", c: "objects" },
  { g: "📀", n: "dvd", k: "DVD 光盘", c: "objects" },
  { g: "🧮", n: "abacus", k: "算盘 计算", c: "objects" },
  { g: "📷", n: "camera", k: "相机 拍照", c: "objects" },
  { g: "📸", n: "camera with flash", k: "相机 闪光灯", c: "objects" },
  { g: "📹", n: "video camera", k: "摄像机 录像 摄像", c: "objects" },
  { g: "📺", n: "television", k: "电视 节目", c: "objects" },
  { g: "📻", n: "radio", k: "收音机 广播", c: "objects" },
  { g: "📼", n: "videocassette", k: "录像带 磁带", c: "objects" },
  { g: "🔍", n: "magnifying glass tilted left", k: "放大镜 搜索 查找", c: "objects" },
  { g: "🔎", n: "magnifying glass tilted right", k: "放大镜 搜索", c: "objects" },
  { g: "🕯", n: "candle", k: "蜡烛 光", c: "objects" },
  { g: "💡", n: "light bulb", k: "灯泡 想法 灵感", c: "objects" },
  { g: "🔦", n: "flashlight", k: "手电筒 照明", c: "objects" },
  { g: "🏮", n: "red paper lantern", k: "灯笼 日本", c: "objects" },
  { g: "📔", n: "notebook with decorative cover", k: "笔记本 本子", c: "objects" },
  { g: "📕", n: "closed book", k: "书 关闭", c: "objects" },
  { g: "📖", n: "open book", k: "书 打开 阅读", c: "objects" },
  { g: "📗", n: "green book", k: "书 绿色", c: "objects" },
  { g: "📘", n: "blue book", k: "书 蓝色", c: "objects" },
  { g: "📙", n: "orange book", k: "书 橙色", c: "objects" },
  { g: "📚", n: "books", k: "书 书籍 阅读", c: "objects" },
  { g: "📓", n: "notebook", k: "笔记本 记录", c: "objects" },
  { g: "📒", n: "ledger", k: "账本 记录", c: "objects" },
  { g: "📃", n: "page with curl", k: "文件 页面", c: "objects" },
  { g: "📜", n: "scroll", k: "卷轴 文件", c: "objects" },
  { g: "📄", n: "page facing up", k: "文件 文档", c: "objects" },
  { g: "📰", n: "newspaper", k: "报纸 新闻", c: "objects" },
  { g: "🗞", n: "rolled-up newspaper", k: "报纸 新闻", c: "objects" },
  { g: "📑", n: "bookmark tabs", k: "书签 标签", c: "objects" },
  { g: "🔖", n: "bookmark", k: "书签 收藏", c: "objects" },
  { g: "📎", n: "paperclip", k: "回形针 附件", c: "objects" },
  { g: "🖇", n: "linked paperclips", k: "回形针 链接", c: "objects" },
  { g: "📏", n: "straight ruler", k: "直尺 测量", c: "objects" },
  { g: "📐", n: "triangular ruler", k: "三角尺 测量", c: "objects" },
  { g: "✂", n: "scissors", k: "剪刀 剪切", c: "objects" },
  { g: "🗂", n: "card index dividers", k: "文件夹 分类", c: "objects" },
  { g: "📁", n: "file folder", k: "文件夹 目录", c: "objects" },
  { g: "📂", n: "open file folder", k: "打开文件夹 目录", c: "objects" },
  { g: "🗃", n: "card file box", k: "卡片盒 档案", c: "objects" },
  { g: "🗄", n: "file cabinet", k: "文件柜 档案", c: "objects" },
  { g: "🗑", n: "wastebasket", k: "垃圾桶 删除", c: "objects" },
  { g: "🔒", n: "locked", k: "锁 加密 安全", c: "objects" },
  { g: "🔓", n: "unlocked", k: "开锁 解锁", c: "objects" },
  { g: "🔏", n: "locked with pen", k: "锁定 签署", c: "objects" },
  { g: "🔐", n: "locked with key", k: "锁定 密钥", c: "objects" },
  { g: "🔑", n: "key", k: "钥匙 解锁 密码", c: "objects" },
  { g: "🗝", n: "old key", k: "旧钥匙 钥匙", c: "objects" },
  { g: "🔨", n: "hammer", k: "锤子 工具", c: "objects" },
  { g: "🪓", n: "axe", k: "斧头 工具", c: "objects" },
  { g: "⛏", n: "pick", k: "镐 工具", c: "objects" },
  { g: "⚒", n: "hammer and pick", k: "锤镐 工具", c: "objects" },
  { g: "🛠", n: "hammer and wrench", k: "工具 维修", c: "objects" },
  { g: "🗡", n: "dagger", k: "匕首 刀", c: "objects" },
  { g: "⚔", n: "crossed swords", k: "交叉剑 战斗", c: "objects" },
  { g: "🔫", n: "water pistol", k: "水枪 玩具", c: "objects" },
  { g: "🏹", n: "bow and arrow", k: "弓箭 射箭", c: "objects" },
  { g: "🛡", n: "shield", k: "盾牌 防护", c: "objects" },
  { g: "🔧", n: "wrench", k: "扳手 工具 维修", c: "objects" },
  { g: "🔩", n: "nut and bolt", k: "螺母螺栓 工具 螺母", c: "objects" },
  { g: "⚙", n: "gear", k: "齿轮 设置 配置", c: "objects" },
  { g: "🗜", n: "clamp", k: "夹具 固定", c: "objects" },
  { g: "⚖", n: "balance scale", k: "天平 公平 权衡", c: "objects" },
  { g: "🔗", n: "link", k: "链接 关联", c: "objects" },
  { g: "⛓", n: "chains", k: "链条 束缚", c: "objects" },
  { g: "🧰", n: "toolbox", k: "工具箱 工具", c: "objects" },
  { g: "🧱", n: "brick", k: "砖块 建筑", c: "objects" },
  { g: "🪨", n: "rock", k: "石头 岩石", c: "objects" },
  { g: "🪵", n: "wood", k: "木头 木材", c: "objects" },
  { g: "🛖", n: "hut", k: "小屋 木屋", c: "objects" },
  { g: "🛗", n: "elevator", k: "电梯 升降", c: "objects" },
  { g: "🛘", n: "elevator", k: "电梯", c: "objects" },
  { g: "🛝", n: "playground slide", k: "滑梯 游乐", c: "objects" },
  { g: "🛞", n: "wheel", k: "轮子 车轮", c: "objects" },
  { g: "🛟", n: "ring buoy", k: "救生圈 安全", c: "objects" },
  { g: "🦯", n: "probing cane", k: "盲杖 无障碍", c: "objects" },
  { g: "🦽", n: "manual wheelchair", k: "手动轮椅 无障碍", c: "objects" },
  { g: "🦼", n: "motorized wheelchair", k: "电动轮椅 无障碍", c: "objects" },
  { g: "🦺", n: "safety vest", k: "安全背心 反光", c: "objects" },
  { g: "🦭", n: "seal", k: "海豹 动物", c: "objects" },
  { g: "🦮", n: "guide dog", k: "导盲犬 无障碍", c: "objects" },
  { g: "🧲", n: "magnet", k: "磁铁 吸引", c: "objects" },
  { g: "🧳", n: "luggage", k: "行李箱 旅行", c: "objects" },
  { g: "🧴", n: "lotion bottle", k: "乳液 护肤", c: "objects" },
  { g: "🧵", n: "thread", k: "线 缝纫", c: "objects" },
  { g: "🧶", n: "yarn", k: "毛线 编织", c: "objects" },
  { g: "🧷", n: "safety pin", k: "别针 安全", c: "objects" },
  { g: "🧸", n: "teddy bear", k: "泰迪熊 玩偶", c: "objects" },
  { g: "🧹", n: "broom", k: "扫帚 打扫", c: "objects" },
  { g: "🧺", n: "basket", k: "篮子 购物", c: "objects" },
  { g: "🧻", n: "roll of paper", k: "卷纸 卫生纸", c: "objects" },
  { g: "🧼", n: "soap", k: "肥皂 清洁", c: "objects" },
  { g: "🧽", n: "sponge", k: "海绵 清洁", c: "objects" },
  { g: "🧾", n: "receipt", k: "收据 小票", c: "objects" },
  { g: "🧿", n: "nazar amulet", k: "护身符 辟邪", c: "objects" },
  { g: "🩰", n: "ballet shoes", k: "芭蕾舞鞋 舞蹈", c: "objects" },
  { g: "🩱", n: "one-piece swimsuit", k: "连体泳衣 游泳", c: "objects" },
  { g: "🩲", n: "briefs", k: "内裤 内衣", c: "objects" },
  { g: "🩳", n: "shorts", k: "短裤 服装", c: "objects" },
  { g: "🩴", n: "thong sandal", k: "人字拖 拖鞋", c: "objects" },
  { g: "🩸", n: "drop of blood", k: "血滴 血液", c: "objects" },
  { g: "🩹", n: "adhesive bandage", k: "创可贴 伤口", c: "objects" },
  { g: "🩺", n: "stethoscope", k: "听诊器 医疗", c: "objects" },
  { g: "🩻", n: "x-ray", k: "X光 医学", c: "objects" },
  { g: "🩼", n: "crutch", k: "拐杖 受伤", c: "objects" },
  { g: "🪀", n: "yo-yo", k: "悠悠球 玩具", c: "objects" },
  { g: "🪁", n: "kite", k: "风筝 玩具", c: "objects" },
  { g: "🪂", n: "parachute", k: "降落伞 跳伞", c: "objects" },
  { g: "🪃", n: "boomerang", k: "回旋镖 玩具", c: "objects" },
  { g: "🪄", n: "magic wand", k: "魔法棒 魔法", c: "objects" },
  { g: "🪅", n: "piñata", k: "皮纳塔 派对", c: "objects" },
  { g: "🪆", n: "nesting dolls", k: "套娃 俄罗斯", c: "objects" },
  { g: "🪐", n: "ringed planet", k: "行星 土星 太空", c: "objects" },
  { g: "🪑", n: "chair", k: "椅子 家具", c: "objects" },
  { g: "🪒", n: "razor", k: "剃须刀 刮胡", c: "objects" },
  { g: "🪔", n: "diya lamp", k: "油灯 排灯节", c: "objects" },
  { g: "🪕", n: "banjo", k: "班卓琴 乐器", c: "objects" },
  { g: "🪖", n: "military helmet", k: "军用头盔 头盔", c: "objects" },
  { g: "🪗", n: "sledge", k: "雪橇", c: "objects" },
  { g: "🪘", n: "accordion", k: "手风琴 乐器", c: "objects" },
  { g: "🪙", n: "coin", k: "硬币 钱", c: "objects" },
  { g: "🪚", n: "carpentry saw", k: "锯子 木工", c: "objects" },
  { g: "🪛", n: "screwdriver", k: "螺丝刀 工具", c: "objects" },
  { g: "🪜", n: "ladder", k: "梯子 攀爬", c: "objects" },
  { g: "🪝", n: "hook", k: "钩子 挂", c: "objects" },
  { g: "🪞", n: "mirror", k: "镜子 反射", c: "objects" },
  { g: "🪟", n: "window", k: "窗户 视窗", c: "objects" },
  { g: "🪠", n: "plunger", k: "皮搋子 疏通", c: "objects" },
  { g: "🪡", n: "sewing needle", k: "缝衣针 缝纫", c: "objects" },
  { g: "🪢", n: "knot", k: "绳结 打结", c: "objects" },
  { g: "🪣", n: "bucket", k: "水桶 桶", c: "objects" },
  { g: "🪤", n: "mouse trap", k: "捕鼠夹 陷阱", c: "objects" },
  { g: "🪥", n: "toothbrush", k: "牙刷 清洁", c: "objects" },
  { g: "🪦", n: "headstone", k: "墓碑 纪念", c: "objects" },
  { g: "🪧", n: "placard", k: "标语牌 抗议", c: "objects" },
  { g: "🪩", n: "mirror ball", k: "镜面球 迪斯科", c: "objects" },
  { g: "🪪", n: "identification card", k: "身份证 证件", c: "objects" },
  { g: "🪫", n: "low battery", k: "电量低 电池", c: "objects" },
  { g: "🪬", n: "hamsa", k: "法蒂玛之手 护身", c: "objects" },
  { g: "💰", n: "money bag", k: "钱袋 金钱 财富", c: "objects" },
  { g: "💴", n: "yen banknote", k: "日元 钞票", c: "objects" },
  { g: "💵", n: "dollar banknote", k: "美元 钞票", c: "objects" },
  { g: "💶", n: "euro banknote", k: "欧元 钞票", c: "objects" },
  { g: "💷", n: "pound banknote", k: "英镑 钞票", c: "objects" },
  { g: "💸", n: "money with wings", k: "飞钱 花钱", c: "objects" },
  { g: "💳", n: "credit card", k: "信用卡 支付", c: "objects" },
  { g: "💹", n: "chart increasing with yen", k: "涨势 金融", c: "objects" },
  { g: "💲", n: "heavy dollar sign", k: "美元 金钱", c: "objects" },
  { g: "💱", n: "currency exchange", k: "汇率 兑换", c: "objects" },
  { g: "📝", n: "memo", k: "备忘录 笔记", c: "objects" },
  { g: "📧", n: "e-mail", k: "邮件 电子邮件", c: "objects" },
  { g: "📨", n: "incoming envelope", k: "收信 邮件", c: "objects" },
  { g: "📩", n: "envelope with arrow", k: "发信 邮件", c: "objects" },
  { g: "📤", n: "outbox tray", k: "发件箱 邮件", c: "objects" },
  { g: "📥", n: "inbox tray", k: "收件箱 邮件", c: "objects" },
  { g: "📦", n: "package", k: "包裹 快递", c: "objects" },
  { g: "📫", n: "closed mailbox with raised flag", k: "邮箱 邮件", c: "objects" },
  { g: "📪", n: "closed mailbox with lowered flag", k: "邮箱 邮件", c: "objects" },
  { g: "📬", n: "open mailbox with raised flag", k: "邮箱 邮件", c: "objects" },
  { g: "📭", n: "open mailbox with lowered flag", k: "邮箱 邮件", c: "objects" },
  { g: "📮", n: "postbox", k: "邮筒 邮箱", c: "objects" },
  { g: "📯", n: "postal horn", k: "邮号 邮政", c: "objects" },
  { g: "📢", n: "loudspeaker", k: "扩音器 公告 广播", c: "objects" },
  { g: "📣", n: "megaphone", k: "喇叭 宣传 公告", c: "objects" },
  { g: "📡", n: "satellite antenna", k: "卫星天线 信号", c: "objects" },
  { g: "📳", n: "vibration mode", k: "震动 手机", c: "objects" },
  { g: "📴", n: "mobile phone off", k: "关机 手机", c: "objects" },
  { g: "📵", n: "no mobile phones", k: "禁止手机", c: "objects" },
  { g: "📶", n: "antenna bars", k: "信号 网络", c: "objects" },
  { g: "🔊", n: "speaker high volume", k: "音量 扬声器 高音量", c: "objects" },
  { g: "✅", n: "check mark button", k: "对勾 完成 正确 通过", c: "symbols" },
  { g: "❌", n: "cross mark", k: "叉 错误 取消 失败", c: "symbols" },
  { g: "❎", n: "cross mark button", k: "叉 错误", c: "symbols" },
  { g: "❗", n: "exclamation mark", k: "感叹号 注意", c: "symbols" },
  { g: "❓", n: "question mark", k: "问号 疑问", c: "symbols" },
  { g: "❕", n: "white exclamation mark", k: "感叹号 提醒", c: "symbols" },
  { g: "⁉", n: "exclamation question mark", k: "疑问 感叹", c: "symbols" },
  { g: "‼", n: "double exclamation mark", k: "双感叹号 注意", c: "symbols" },
  { g: "🛑", n: "stop sign", k: "停止 停", c: "symbols" },
  { g: "🏴", n: "black flag", k: "黑旗 旗帜", c: "symbols" },
  { g: "🏳", n: "white flag", k: "白旗 投降", c: "symbols" },
  { g: "⚑", n: "black flag", k: "黑旗", c: "symbols" },
  { g: "⚐", n: "white flag", k: "白旗", c: "symbols" },
  { g: "⬆", n: "up arrow", k: "向上 箭头 上箭头", c: "symbols" },
  { g: "↗", n: "up-right arrow", k: "右上 箭头", c: "symbols" },
  { g: "➡", n: "right arrow", k: "向右 箭头 下一步 右箭头", c: "symbols" },
  { g: "↘", n: "down-right arrow", k: "右下 箭头", c: "symbols" },
  { g: "⬇", n: "down arrow", k: "向下 箭头 下箭头", c: "symbols" },
  { g: "↙", n: "down-left arrow", k: "左下 箭头", c: "symbols" },
  { g: "⬅", n: "left arrow", k: "向左 箭头 返回 左箭头", c: "symbols" },
  { g: "↖", n: "up-left arrow", k: "左上 箭头", c: "symbols" },
  { g: "↕", n: "up-down arrow", k: "上下 箭头", c: "symbols" },
  { g: "↔", n: "left-right arrow", k: "左右 箭头", c: "symbols" },
  { g: "↩", n: "right arrow curving left", k: "返回 回复", c: "symbols" },
  { g: "↪", n: "left arrow curving right", k: "转发 前进", c: "symbols" },
  { g: "⤴", n: "right arrow curving up", k: "向上弯 箭头 弯箭头", c: "symbols" },
  { g: "⤵", n: "right arrow curving down", k: "向下弯 箭头 弯箭头", c: "symbols" },
  { g: "🔃", n: "clockwise vertical arrows", k: "刷新 循环 同步", c: "symbols" },
  { g: "🔄", n: "anticlockwise arrows button", k: "重试 刷新", c: "symbols" },
  { g: "🔙", n: "BACK arrow", k: "返回 后退", c: "symbols" },
  { g: "🔚", n: "END arrow", k: "结束 末尾", c: "symbols" },
  { g: "🔛", n: "ON arrow", k: "开启 上", c: "symbols" },
  { g: "🔜", n: "SOON arrow", k: "即将 稍后", c: "symbols" },
  { g: "🔝", n: "TOP arrow", k: "顶部 置顶", c: "symbols" },
  { g: "🔀", n: "shuffle tracks button", k: "随机 打乱", c: "symbols" },
  { g: "🔁", n: "repeat button", k: "重复 循环", c: "symbols" },
  { g: "🔂", n: "repeat single button", k: "单曲循环 重复", c: "symbols" },
  { g: "▶", n: "play button", k: "播放 开始", c: "symbols" },
  { g: "⏩", n: "fast-forward button", k: "快进 加速", c: "symbols" },
  { g: "⏭", n: "next track button", k: "下一首 下一个", c: "symbols" },
  { g: "⏯", n: "play or pause button", k: "播放暂停", c: "symbols" },
  { g: "◀", n: "reverse button", k: "倒放 反向", c: "symbols" },
  { g: "⏪", n: "fast reverse button", k: "快退 倒退", c: "symbols" },
  { g: "⏮", n: "last track button", k: "上一首 上一个", c: "symbols" },
  { g: "🔼", n: "upwards button", k: "向上 增加", c: "symbols" },
  { g: "⏫", n: "fast up button", k: "快速向上", c: "symbols" },
  { g: "🔽", n: "downwards button", k: "向下 减少", c: "symbols" },
  { g: "⏬", n: "fast down button", k: "快速向下", c: "symbols" },
  { g: "⏸", n: "pause button", k: "暂停", c: "symbols" },
  { g: "⏹", n: "stop button", k: "停止", c: "symbols" },
  { g: "⏺", n: "record button", k: "录制 录音", c: "symbols" },
  { g: "⏱", n: "stopwatch", k: "秒表 计时", c: "symbols" },
  { g: "⏲", n: "timer clock", k: "定时器 计时", c: "symbols" },
  { g: "⏰", n: "alarm clock", k: "闹钟 提醒", c: "symbols" },
  { g: "🕰", n: "mantelpiece clock", k: "座钟 时钟", c: "symbols" },
  { g: "⌛", n: "hourglass done", k: "沙漏 时间到", c: "symbols" },
  { g: "⏳", n: "hourglass not done", k: "沙漏 计时中", c: "symbols" },
  { g: "🔆", n: "brightness high", k: "亮度高 明亮", c: "symbols" },
  { g: "🔅", n: "brightness low", k: "亮度低 暗", c: "symbols" },
  { g: "🔇", n: "muted speaker", k: "静音 无声", c: "symbols" },
  { g: "🔈", n: "speaker low volume", k: "低音量 音量", c: "symbols" },
  { g: "🔉", n: "speaker medium volume", k: "中音量 音量", c: "symbols" },
  { g: "🔔", n: "bell", k: "铃铛 提醒 通知", c: "symbols" },
  { g: "🔕", n: "bell with slash", k: "静音 关闭提醒", c: "symbols" },
  { g: "♻", n: "recycling symbol", k: "回收 环保", c: "symbols" },
  { g: "♾", n: "infinity", k: "无限 无穷", c: "symbols" },
  { g: "♿", n: "wheelchair symbol", k: "无障碍 轮椅", c: "symbols" },
  { g: "⚓", n: "anchor", k: "锚 停泊", c: "symbols" },
  { g: "⚪", n: "white circle", k: "白圈 圆", c: "symbols" },
  { g: "⚫", n: "black circle", k: "黑圈 圆", c: "symbols" },
  { g: "⚰", n: "coffin", k: "棺材 死亡", c: "symbols" },
  { g: "⚱", n: "funeral urn", k: "骨灰盒 葬礼", c: "symbols" },
  { g: "⛄", n: "snowman without snow", k: "雪人 冬天", c: "symbols" },
  { g: "⛎", n: "Ophiuchus", k: "蛇夫座 星座", c: "symbols" },
  { g: "⛔", n: "no entry", k: "禁止通行", c: "symbols" },
  { g: "⛽", n: "fuel pump", k: "加油站 加油", c: "symbols" },
  { g: "✈", n: "airplane", k: "飞机 航班", c: "symbols" },
  { g: "✉", n: "envelope", k: "信封", c: "symbols" },
  { g: "✊", n: "raised fist", k: "举拳 加油", c: "symbols" },
  { g: "✏", n: "pencil", k: "铅笔 编辑", c: "symbols" },
  { g: "✒", n: "black nib", k: "钢笔尖 编辑", c: "symbols" },
  { g: "✔", n: "check mark", k: "对勾 完成", c: "symbols" },
  { g: "✖", n: "multiply", k: "乘号 关闭", c: "symbols" },
  { g: "✝", n: "latin cross", k: "十字架 宗教", c: "symbols" },
  { g: "✡", n: "star of David", k: "六芒星 犹太", c: "symbols" },
  { g: "✨", n: "sparkles", k: "闪光 新 闪亮", c: "symbols" },
  { g: "✳", n: "eight-spoked asterisk", k: "星号", c: "symbols" },
  { g: "✴", n: "eight-pointed star", k: "八角星", c: "symbols" },
  { g: "❇", n: "sparkle", k: "闪光", c: "symbols" },
  { g: "❔", n: "white question mark", k: "问号", c: "symbols" },
  { g: "➕", n: "plus", k: "加号 添加", c: "symbols" },
  { g: "➖", n: "minus", k: "减号 移除", c: "symbols" },
  { g: "➗", n: "divide", k: "除号", c: "symbols" },
  { g: "➰", n: "curly loop", k: "卷曲环", c: "symbols" },
  { g: "➿", n: "double curly loop", k: "双卷曲环", c: "symbols" },
  { g: "⬛", n: "black large square", k: "黑方块", c: "symbols" },
  { g: "⬜", n: "white large square", k: "白方块", c: "symbols" },
  { g: "⭕", n: "hollow red circle", k: "红圈 正确", c: "symbols" },
  { g: "〰", n: "wavy dash", k: "波浪线", c: "symbols" },
  { g: "〽", n: "part alternation mark", k: "交替标记", c: "symbols" },
  { g: "㊗", n: "congratulations", k: "祝贺 恭喜", c: "symbols" },
  { g: "㊙", n: "secret", k: "秘密", c: "symbols" },
  { g: "💣", n: "bomb", k: "炸弹 爆炸", c: "symbols" },
  { g: "💦", n: "sweat droplets", k: "汗滴", c: "symbols" },
  { g: "💼", n: "briefcase", k: "公文包 工作", c: "symbols" },
  { g: "📅", n: "calendar", k: "日历 日期", c: "symbols" },
  { g: "📆", n: "tear-off calendar", k: "日历 日期", c: "symbols" },
  { g: "📇", n: "card index", k: "卡片索引", c: "symbols" },
  { g: "📈", n: "chart increasing", k: "上升图表 增长", c: "symbols" },
  { g: "📉", n: "chart decreasing", k: "下降图表 减少", c: "symbols" },
  { g: "📊", n: "bar chart", k: "柱状图 数据", c: "symbols" },
  { g: "📋", n: "clipboard", k: "剪贴板 清单", c: "symbols" },
  { g: "📌", n: "pushpin", k: "图钉 固定", c: "symbols" },
  { g: "📍", n: "round pushpin", k: "图钉 位置", c: "symbols" },
  { g: "📛", n: "name badge", k: "名牌 胸牌", c: "symbols" },
  { g: "📽", n: "film projector", k: "放映机 电影", c: "symbols" },
  { g: "📾", n: "portable stereo", k: "音响 音乐", c: "symbols" },
  { g: "📿", n: "prayer beads", k: "念珠 祈祷", c: "symbols" },
  { g: "🔘", n: "radio button", k: "单选按钮", c: "symbols" },
  { g: "🔞", n: "no one under eighteen", k: "十八禁 限制", c: "symbols" },
  { g: "🔟", n: "keycap ten", k: "十 数字", c: "symbols" },
  { g: "🔠", n: "input latin uppercase", k: "大写字母 输入", c: "symbols" },
  { g: "🔡", n: "input latin lowercase", k: "小写字母 输入", c: "symbols" },
  { g: "🔢", n: "input numbers", k: "数字 输入", c: "symbols" },
  { g: "🔣", n: "input symbols", k: "符号 输入", c: "symbols" },
  { g: "🔤", n: "input latin letters", k: "字母 输入", c: "symbols" },
  { g: "🔬", n: "microscope", k: "显微镜 科学", c: "symbols" },
  { g: "🔭", n: "telescope", k: "望远镜 天文", c: "symbols" },
  { g: "🔮", n: "crystal ball", k: "水晶球 占卜", c: "symbols" },
  { g: "🔯", n: "dotted six-pointed star", k: "六芒星", c: "symbols" },
  { g: "🔰", n: "Japanese symbol for beginner", k: "新手 初学者", c: "symbols" },
  { g: "🔱", n: "trident emblem", k: "三叉戟 标志", c: "symbols" },
  { g: "🔲", n: "black square button", k: "黑色方块按钮", c: "symbols" },
  { g: "🔳", n: "white square button", k: "白色方块按钮", c: "symbols" },
  { g: "🔴", n: "red circle", k: "红圈", c: "symbols" },
  { g: "🔵", n: "blue circle", k: "蓝圈", c: "symbols" },
  { g: "🔶", n: "large orange diamond", k: "橙色菱形", c: "symbols" },
  { g: "🔷", n: "large blue diamond", k: "蓝色菱形", c: "symbols" },
  { g: "🔸", n: "small orange diamond", k: "橙色小菱形", c: "symbols" },
  { g: "🔹", n: "small blue diamond", k: "蓝色小菱形", c: "symbols" },
  { g: "🔺", n: "red triangle pointed up", k: "红色向上三角", c: "symbols" },
  { g: "🔻", n: "red triangle pointed down", k: "红色向下三角", c: "symbols" },
  { g: "🎌", n: "crossed flags", k: "交叉旗 庆祝", c: "flags" },
  { g: "🏳️‍🌈", n: "rainbow flag", k: "彩虹旗 骄傲", c: "flags" },
  { g: "🏳️‍⚧", n: "transgender flag", k: "跨性别旗", c: "flags" },
  { g: "🏴‍☠", n: "pirate flag", k: "海盗旗", c: "flags" },
  { g: "🇦🇨", n: "flag Ascension Island", k: "国旗 阿森松岛", c: "flags" },
  { g: "🇦🇩", n: "flag Andorra", k: "国旗 安道尔", c: "flags" },
  { g: "🇦🇪", n: "flag United Arab Emirates", k: "国旗 阿联酋", c: "flags" },
  { g: "🇦🇫", n: "flag Afghanistan", k: "国旗 阿富汗", c: "flags" },
  { g: "🇦🇬", n: "flag Antigua and Barbuda", k: "国旗 安提瓜", c: "flags" },
  { g: "🇦🇮", n: "flag Anguilla", k: "国旗 安圭拉", c: "flags" },
  { g: "🇦🇱", n: "flag Albania", k: "国旗 阿尔巴尼亚", c: "flags" },
  { g: "🇦🇲", n: "flag Armenia", k: "国旗 亚美尼亚", c: "flags" },
  { g: "🇦🇴", n: "flag Angola", k: "国旗 安哥拉", c: "flags" },
  { g: "🇦🇶", n: "flag Antarctica", k: "国旗 南极洲", c: "flags" },
  { g: "🇦🇷", n: "flag Argentina", k: "国旗 阿根廷", c: "flags" },
  { g: "🇦🇸", n: "flag American Samoa", k: "国旗 美属萨摩亚", c: "flags" },
  { g: "🇦🇹", n: "flag Austria", k: "国旗 奥地利", c: "flags" },
  { g: "🇦🇺", n: "flag Australia", k: "国旗 澳大利亚", c: "flags" },
  { g: "🇦🇼", n: "flag Aruba", k: "国旗 阿鲁巴", c: "flags" },
  { g: "🇦🇽", n: "flag Aland Islands", k: "国旗 奥兰群岛", c: "flags" },
  { g: "🇦🇿", n: "flag Azerbaijan", k: "国旗 阿塞拜疆", c: "flags" },
  { g: "🇧🇦", n: "flag Bosnia and Herzegovina", k: "国旗 波黑", c: "flags" },
  { g: "🇧🇧", n: "flag Barbados", k: "国旗 巴巴多斯", c: "flags" },
  { g: "🇧🇩", n: "flag Bangladesh", k: "国旗 孟加拉国", c: "flags" },
  { g: "🇧🇪", n: "flag Belgium", k: "国旗 比利时", c: "flags" },
  { g: "🇧🇫", n: "flag Burkina Faso", k: "国旗 布基纳法索", c: "flags" },
  { g: "🇧🇬", n: "flag Bulgaria", k: "国旗 保加利亚", c: "flags" },
  { g: "🇧🇭", n: "flag Bahrain", k: "国旗 巴林", c: "flags" },
  { g: "🇧🇮", n: "flag Burundi", k: "国旗 布隆迪", c: "flags" },
  { g: "🇧🇯", n: "flag Benin", k: "国旗 贝宁", c: "flags" },
  { g: "🇧🇱", n: "flag St Barthelemy", k: "国旗", c: "flags" },
  { g: "🇧🇲", n: "flag Bermuda", k: "国旗 百慕大", c: "flags" },
  { g: "🇧🇳", n: "flag Brunei", k: "国旗 文莱", c: "flags" },
  { g: "🇧🇴", n: "flag Bolivia", k: "国旗 玻利维亚", c: "flags" },
  { g: "🇧🇶", n: "flag Caribbean Netherlands", k: "国旗", c: "flags" },
  { g: "🇧🇷", n: "flag Brazil", k: "国旗 巴西", c: "flags" },
  { g: "🇧🇸", n: "flag Bahamas", k: "国旗 巴哈马", c: "flags" },
  { g: "🇧🇹", n: "flag Bhutan", k: "国旗 不丹", c: "flags" },
  { g: "🇧🇼", n: "flag Botswana", k: "国旗 博茨瓦纳", c: "flags" },
  { g: "🇧🇾", n: "flag Belarus", k: "国旗 白俄罗斯", c: "flags" },
  { g: "🇧🇿", n: "flag Belize", k: "国旗 伯利兹", c: "flags" },
  { g: "🇨🇦", n: "flag Canada", k: "国旗 加拿大", c: "flags" },
  { g: "🇨🇨", n: "flag Cocos Islands", k: "国旗", c: "flags" },
  { g: "🇨🇩", n: "flag Congo Kinshasa", k: "国旗 刚果金", c: "flags" },
  { g: "🇨🇫", n: "flag Central African Republic", k: "国旗 中非", c: "flags" },
  { g: "🇨🇬", n: "flag Congo Brazzaville", k: "国旗 刚果布", c: "flags" },
  { g: "🇨🇭", n: "flag Switzerland", k: "国旗 瑞士", c: "flags" },
  { g: "🇨🇮", n: "flag Cote d Ivoire", k: "国旗 科特迪瓦", c: "flags" },
  { g: "🇨🇰", n: "flag Cook Islands", k: "国旗 库克群岛", c: "flags" },
  { g: "🇨🇱", n: "flag Chile", k: "国旗 智利", c: "flags" },
  { g: "🇨🇲", n: "flag Cameroon", k: "国旗 喀麦隆", c: "flags" },
  { g: "🇨🇳", n: "flag China", k: "国旗 中国 五星红旗", c: "flags" },
  { g: "🇨🇴", n: "flag Colombia", k: "国旗 哥伦比亚", c: "flags" },
  { g: "🇨🇵", n: "flag Clipperton Island", k: "国旗", c: "flags" },
  { g: "🇨🇷", n: "flag Costa Rica", k: "国旗 哥斯达黎加", c: "flags" },
  { g: "🇨🇺", n: "flag Cuba", k: "国旗 古巴", c: "flags" },
  { g: "🇨🇻", n: "flag Cape Verde", k: "国旗 佛得角", c: "flags" },
  { g: "🇨🇼", n: "flag Curacao", k: "国旗 库拉索", c: "flags" },
  { g: "🇨🇽", n: "flag Christmas Island", k: "国旗", c: "flags" },
  { g: "🇨🇾", n: "flag Cyprus", k: "国旗 塞浦路斯", c: "flags" },
  { g: "🇨🇿", n: "flag Czechia", k: "国旗 捷克", c: "flags" },
  { g: "🇩🇪", n: "flag Germany", k: "国旗 德国", c: "flags" },
  { g: "🇩🇬", n: "flag Diego Garcia", k: "国旗", c: "flags" },
  { g: "🇩🇯", n: "flag Djibouti", k: "国旗 吉布提", c: "flags" },
  { g: "🇩🇰", n: "flag Denmark", k: "国旗 丹麦", c: "flags" },
  { g: "🇩🇲", n: "flag Dominica", k: "国旗 多米尼克", c: "flags" },
  { g: "🇩🇴", n: "flag Dominican Republic", k: "国旗 多米尼加", c: "flags" },
  { g: "🇩🇿", n: "flag Algeria", k: "国旗 阿尔及利亚", c: "flags" },
  { g: "🇪🇦", n: "flag Ceuta and Melilla", k: "国旗", c: "flags" },
  { g: "🇪🇨", n: "flag Ecuador", k: "国旗 厄瓜多尔", c: "flags" },
  { g: "🇪🇪", n: "flag Estonia", k: "国旗 爱沙尼亚", c: "flags" },
  { g: "🇪🇬", n: "flag Egypt", k: "国旗 埃及", c: "flags" },
  { g: "🇪🇭", n: "flag Western Sahara", k: "国旗 西撒哈拉", c: "flags" },
  { g: "🇪🇷", n: "flag Eritrea", k: "国旗 厄立特里亚", c: "flags" },
  { g: "🇪🇸", n: "flag Spain", k: "国旗 西班牙", c: "flags" },
  { g: "🇪🇹", n: "flag Ethiopia", k: "国旗 埃塞俄比亚", c: "flags" },
  { g: "🇪🇺", n: "flag European Union", k: "旗帜 欧盟", c: "flags" },
  { g: "🇫🇮", n: "flag Finland", k: "国旗 芬兰", c: "flags" },
  { g: "🇫🇯", n: "flag Fiji", k: "国旗 斐济", c: "flags" },
  { g: "🇫🇰", n: "flag Falkland Islands", k: "国旗", c: "flags" },
  { g: "🇫🇲", n: "flag Micronesia", k: "国旗 密克罗尼西亚", c: "flags" },
  { g: "🇫🇴", n: "flag Faroe Islands", k: "国旗 法罗群岛", c: "flags" },
  { g: "🇫🇷", n: "flag France", k: "国旗 法国", c: "flags" },
  { g: "🇬🇦", n: "flag Gabon", k: "国旗 加蓬", c: "flags" },
  { g: "🇬🇧", n: "flag United Kingdom", k: "国旗 英国", c: "flags" },
  { g: "🇬🇩", n: "flag Grenada", k: "国旗 格林纳达", c: "flags" },
  { g: "🇬🇪", n: "flag Georgia", k: "国旗 格鲁吉亚", c: "flags" },
  { g: "🇬🇫", n: "flag French Guiana", k: "国旗 法属圭亚那", c: "flags" },
  { g: "🇬🇬", n: "flag Guernsey", k: "国旗 根西岛", c: "flags" },
  { g: "🇬🇭", n: "flag Ghana", k: "国旗 加纳", c: "flags" },
  { g: "🇬🇮", n: "flag Gibraltar", k: "国旗 直布罗陀", c: "flags" },
  { g: "🇬🇱", n: "flag Greenland", k: "国旗 格陵兰", c: "flags" },
  { g: "🇬🇲", n: "flag Gambia", k: "国旗 冈比亚", c: "flags" },
  { g: "🇬🇳", n: "flag Guinea", k: "国旗 几内亚", c: "flags" },
  { g: "🇬🇵", n: "flag Guadeloupe", k: "国旗 瓜德罗普", c: "flags" },
  { g: "🇬🇶", n: "flag Equatorial Guinea", k: "国旗 赤道几内亚", c: "flags" },
  { g: "🇬🇷", n: "flag Greece", k: "国旗 希腊", c: "flags" },
  { g: "🇬🇸", n: "flag South Georgia", k: "国旗", c: "flags" },
  { g: "🇬🇹", n: "flag Guatemala", k: "国旗 危地马拉", c: "flags" },
  { g: "🇬🇺", n: "flag Guam", k: "国旗 关岛", c: "flags" },
  { g: "🇬🇼", n: "flag Guinea-Bissau", k: "国旗 几内亚比绍", c: "flags" },
  { g: "🇬🇾", n: "flag Guyana", k: "国旗 圭亚那", c: "flags" },
  { g: "🇭🇰", n: "flag Hong Kong SAR China", k: "国旗 香港", c: "flags" },
  { g: "🇭🇲", n: "flag Heard and McDonald Islands", k: "国旗", c: "flags" },
  { g: "🇭🇳", n: "flag Honduras", k: "国旗 洪都拉斯", c: "flags" },
  { g: "🇭🇷", n: "flag Croatia", k: "国旗 克罗地亚", c: "flags" },
  { g: "🇭🇹", n: "flag Haiti", k: "国旗 海地", c: "flags" },
  { g: "🇭🇺", n: "flag Hungary", k: "国旗 匈牙利", c: "flags" },
  { g: "🇮🇨", n: "flag Canary Islands", k: "国旗", c: "flags" },
  { g: "🇮🇩", n: "flag Indonesia", k: "国旗 印度尼西亚", c: "flags" },
  { g: "🇮🇪", n: "flag Ireland", k: "国旗 爱尔兰", c: "flags" },
  { g: "🇮🇱", n: "flag Israel", k: "国旗 以色列", c: "flags" },
  { g: "🇮🇲", n: "flag Isle of Man", k: "国旗 马恩岛", c: "flags" },
  { g: "🇮🇳", n: "flag India", k: "国旗 印度", c: "flags" },
  { g: "🇮🇴", n: "flag British Indian Ocean Territory", k: "国旗", c: "flags" },
  { g: "🇮🇶", n: "flag Iraq", k: "国旗 伊拉克", c: "flags" },
  { g: "🇮🇷", n: "flag Iran", k: "国旗 伊朗", c: "flags" },
  { g: "🇮🇸", n: "flag Iceland", k: "国旗 冰岛", c: "flags" },
  { g: "🇮🇹", n: "flag Italy", k: "国旗 意大利", c: "flags" },
  { g: "🇯🇪", n: "flag Jersey", k: "国旗 泽西岛", c: "flags" },
  { g: "🇯🇲", n: "flag Jamaica", k: "国旗 牙买加", c: "flags" },
  { g: "🇯🇴", n: "flag Jordan", k: "国旗 约旦", c: "flags" },
  { g: "🇯🇵", n: "flag Japan", k: "国旗 日本", c: "flags" },
  { g: "🇰🇪", n: "flag Kenya", k: "国旗 肯尼亚", c: "flags" },
  { g: "🇰🇬", n: "flag Kyrgyzstan", k: "国旗 吉尔吉斯斯坦", c: "flags" },
  { g: "🇰🇭", n: "flag Cambodia", k: "国旗 柬埔寨", c: "flags" },
  { g: "🇰🇮", n: "flag Kiribati", k: "国旗 基里巴斯", c: "flags" },
  { g: "🇰🇲", n: "flag Comoros", k: "国旗 科摩罗", c: "flags" },
  { g: "🇰🇳", n: "flag St Kitts and Nevis", k: "国旗", c: "flags" },
  { g: "🇰🇵", n: "flag North Korea", k: "国旗 朝鲜", c: "flags" },
  { g: "🇰🇷", n: "flag South Korea", k: "国旗 韩国", c: "flags" },
  { g: "🇰🇼", n: "flag Kuwait", k: "国旗 科威特", c: "flags" },
  { g: "🇰🇾", n: "flag Cayman Islands", k: "国旗 开曼群岛", c: "flags" },
  { g: "🇰🇿", n: "flag Kazakhstan", k: "国旗 哈萨克斯坦", c: "flags" },
  { g: "🇱🇦", n: "flag Laos", k: "国旗 老挝", c: "flags" },
  { g: "🇱🇧", n: "flag Lebanon", k: "国旗 黎巴嫩", c: "flags" },
  { g: "🇱🇨", n: "flag St Lucia", k: "国旗 圣卢西亚", c: "flags" },
  { g: "🇱🇮", n: "flag Liechtenstein", k: "国旗 列支敦士登", c: "flags" },
  { g: "🇱🇰", n: "flag Sri Lanka", k: "国旗 斯里兰卡", c: "flags" },
  { g: "🇱🇷", n: "flag Liberia", k: "国旗 利比里亚", c: "flags" },
  { g: "🇱🇸", n: "flag Lesotho", k: "国旗 莱索托", c: "flags" },
  { g: "🇱🇹", n: "flag Lithuania", k: "国旗 立陶宛", c: "flags" },
  { g: "🇱🇺", n: "flag Luxembourg", k: "国旗 卢森堡", c: "flags" },
  { g: "🇱🇻", n: "flag Latvia", k: "国旗 拉脱维亚", c: "flags" },
  { g: "🇱🇾", n: "flag Libya", k: "国旗 利比亚", c: "flags" },
  { g: "🇲🇦", n: "flag Morocco", k: "国旗 摩洛哥", c: "flags" },
  { g: "🇲🇨", n: "flag Monaco", k: "国旗 摩纳哥", c: "flags" },
  { g: "🇲🇩", n: "flag Moldova", k: "国旗 摩尔多瓦", c: "flags" },
  { g: "🇲🇪", n: "flag Montenegro", k: "国旗 黑山", c: "flags" },
  { g: "🇲🇫", n: "flag St Martin", k: "国旗", c: "flags" },
  { g: "🇲🇬", n: "flag Madagascar", k: "国旗 马达加斯加", c: "flags" },
  { g: "🇲🇭", n: "flag Marshall Islands", k: "国旗 马绍尔群岛", c: "flags" },
  { g: "🇲🇰", n: "flag North Macedonia", k: "国旗 北马其顿", c: "flags" },
  { g: "🇲🇱", n: "flag Mali", k: "国旗 马里", c: "flags" },
  { g: "🇲🇲", n: "flag Myanmar", k: "国旗 缅甸", c: "flags" },
  { g: "🇲🇳", n: "flag Mongolia", k: "国旗 蒙古", c: "flags" },
  { g: "🇲🇴", n: "flag Macao SAR China", k: "国旗 澳门", c: "flags" },
  { g: "🇲🇵", n: "flag Northern Mariana Islands", k: "国旗", c: "flags" },
  { g: "🇲🇶", n: "flag Martinique", k: "国旗 马提尼克", c: "flags" },
  { g: "🇲🇷", n: "flag Mauritania", k: "国旗 毛里塔尼亚", c: "flags" },
  { g: "🇲🇸", n: "flag Montserrat", k: "国旗 蒙特塞拉特", c: "flags" },
  { g: "🇲🇹", n: "flag Malta", k: "国旗 马耳他", c: "flags" },
  { g: "🇲🇺", n: "flag Mauritius", k: "国旗 毛里求斯", c: "flags" },
  { g: "🇲🇻", n: "flag Maldives", k: "国旗 马尔代夫", c: "flags" },
  { g: "🇲🇼", n: "flag Malawi", k: "国旗 马拉维", c: "flags" },
  { g: "🇲🇽", n: "flag Mexico", k: "国旗 墨西哥", c: "flags" },
  { g: "🇲🇾", n: "flag Malaysia", k: "国旗 马来西亚", c: "flags" },
  { g: "🇲🇿", n: "flag Mozambique", k: "国旗 莫桑比克", c: "flags" },
  { g: "🇳🇦", n: "flag Namibia", k: "国旗 纳米比亚", c: "flags" },
  { g: "🇳🇨", n: "flag New Caledonia", k: "国旗 新喀里多尼亚", c: "flags" },
  { g: "🇳🇪", n: "flag Niger", k: "国旗 尼日尔", c: "flags" },
  { g: "🇳🇫", n: "flag Norfolk Island", k: "国旗 诺福克岛", c: "flags" },
  { g: "🇳🇬", n: "flag Nigeria", k: "国旗 尼日利亚", c: "flags" },
  { g: "🇳🇮", n: "flag Nicaragua", k: "国旗 尼加拉瓜", c: "flags" },
  { g: "🇳🇱", n: "flag Netherlands", k: "国旗 荷兰", c: "flags" },
  { g: "🇳🇴", n: "flag Norway", k: "国旗 挪威", c: "flags" },
  { g: "🇳🇵", n: "flag Nepal", k: "国旗 尼泊尔", c: "flags" },
  { g: "🇳🇷", n: "flag Nauru", k: "国旗 瑙鲁", c: "flags" },
  { g: "🇳🇺", n: "flag Niue", k: "国旗 纽埃", c: "flags" },
  { g: "🇳🇿", n: "flag New Zealand", k: "国旗 新西兰", c: "flags" },
  { g: "🇴🇲", n: "flag Oman", k: "国旗 阿曼", c: "flags" },
  { g: "🇵🇦", n: "flag Panama", k: "国旗 巴拿马", c: "flags" },
  { g: "🇵🇪", n: "flag Peru", k: "国旗 秘鲁", c: "flags" },
  { g: "🇵🇫", n: "flag French Polynesia", k: "国旗 法属波利尼西亚", c: "flags" },
  { g: "🇵🇬", n: "flag Papua New Guinea", k: "国旗 巴布亚新几内亚", c: "flags" },
  { g: "🇵🇭", n: "flag Philippines", k: "国旗 菲律宾", c: "flags" },
  { g: "🇵🇰", n: "flag Pakistan", k: "国旗 巴基斯坦", c: "flags" },
  { g: "🇵🇱", n: "flag Poland", k: "国旗 波兰", c: "flags" },
  { g: "🇵🇲", n: "flag St Pierre and Miquelon", k: "国旗", c: "flags" },
  { g: "🇵🇳", n: "flag Pitcairn Islands", k: "国旗", c: "flags" },
  { g: "🇵🇷", n: "flag Puerto Rico", k: "国旗 波多黎各", c: "flags" },
  { g: "🇵🇸", n: "flag Palestinian Territories", k: "国旗 巴勒斯坦", c: "flags" },
  { g: "🇵🇹", n: "flag Portugal", k: "国旗 葡萄牙", c: "flags" },
  { g: "🇵🇼", n: "flag Palau", k: "国旗 帕劳", c: "flags" },
  { g: "🇵🇾", n: "flag Paraguay", k: "国旗 巴拉圭", c: "flags" },
  { g: "🇶🇦", n: "flag Qatar", k: "国旗 卡塔尔", c: "flags" },
  { g: "🇷🇪", n: "flag Reunion", k: "国旗 留尼汪", c: "flags" },
  { g: "🇷🇴", n: "flag Romania", k: "国旗 罗马尼亚", c: "flags" },
  { g: "🇷🇸", n: "flag Serbia", k: "国旗 塞尔维亚", c: "flags" },
  { g: "🇷🇺", n: "flag Russia", k: "国旗 俄罗斯", c: "flags" },
  { g: "🇷🇼", n: "flag Rwanda", k: "国旗 卢旺达", c: "flags" },
  { g: "🇸🇦", n: "flag Saudi Arabia", k: "国旗 沙特", c: "flags" },
  { g: "🇸🇧", n: "flag Solomon Islands", k: "国旗 所罗门群岛", c: "flags" },
  { g: "🇸🇨", n: "flag Seychelles", k: "国旗 塞舌尔", c: "flags" },
  { g: "🇸🇩", n: "flag Sudan", k: "国旗 苏丹", c: "flags" },
  { g: "🇸🇪", n: "flag Sweden", k: "国旗 瑞典", c: "flags" },
  { g: "🇸🇬", n: "flag Singapore", k: "国旗 新加坡", c: "flags" },
  { g: "🇸🇭", n: "flag St Helena", k: "国旗", c: "flags" },
  { g: "🇸🇮", n: "flag Slovenia", k: "国旗 斯洛文尼亚", c: "flags" },
  { g: "🇸🇯", n: "flag Svalbard and Jan Mayen", k: "国旗", c: "flags" },
  { g: "🇸🇰", n: "flag Slovakia", k: "国旗 斯洛伐克", c: "flags" },
  { g: "🇸🇱", n: "flag Sierra Leone", k: "国旗 塞拉利昂", c: "flags" },
  { g: "🇸🇲", n: "flag San Marino", k: "国旗 圣马力诺", c: "flags" },
  { g: "🇸🇳", n: "flag Senegal", k: "国旗 塞内加尔", c: "flags" },
  { g: "🇸🇴", n: "flag Somalia", k: "国旗 索马里", c: "flags" },
  { g: "🇸🇷", n: "flag Suriname", k: "国旗 苏里南", c: "flags" },
  { g: "🇸🇸", n: "flag South Sudan", k: "国旗 南苏丹", c: "flags" },
  { g: "🇸🇹", n: "flag Sao Tome and Principe", k: "国旗", c: "flags" },
  { g: "🇸🇻", n: "flag El Salvador", k: "国旗 萨尔瓦多", c: "flags" },
  { g: "🇸🇽", n: "flag Sint Maarten", k: "国旗", c: "flags" },
  { g: "🇸🇾", n: "flag Syria", k: "国旗 叙利亚", c: "flags" },
  { g: "🇸🇿", n: "flag Eswatini", k: "国旗 斯威士兰", c: "flags" },
  { g: "🇹🇦", n: "flag Tristan da Cunha", k: "国旗", c: "flags" },
  { g: "🇹🇨", n: "flag Turks and Caicos Islands", k: "国旗", c: "flags" },
  { g: "🇹🇩", n: "flag Chad", k: "国旗 乍得", c: "flags" },
  { g: "🇹🇫", n: "flag French Southern Territories", k: "国旗", c: "flags" },
  { g: "🇹🇬", n: "flag Togo", k: "国旗 多哥", c: "flags" },
  { g: "🇹🇭", n: "flag Thailand", k: "国旗 泰国", c: "flags" },
  { g: "🇹🇯", n: "flag Tajikistan", k: "国旗 塔吉克斯坦", c: "flags" },
  { g: "🇹🇰", n: "flag Tokelau", k: "国旗 托克劳", c: "flags" },
  { g: "🇹🇱", n: "flag Timor-Leste", k: "国旗 东帝汶", c: "flags" },
  { g: "🇹🇲", n: "flag Turkmenistan", k: "国旗 土库曼斯坦", c: "flags" },
  { g: "🇹🇳", n: "flag Tunisia", k: "国旗 突尼斯", c: "flags" },
  { g: "🇹🇴", n: "flag Tonga", k: "国旗 汤加", c: "flags" },
  { g: "🇹🇷", n: "flag Turkey", k: "国旗 土耳其", c: "flags" },
  { g: "🇹🇹", n: "flag Trinidad and Tobago", k: "国旗 特立尼达", c: "flags" },
  { g: "🇹🇻", n: "flag Tuvalu", k: "国旗 图瓦卢", c: "flags" },
  { g: "🇹🇼", n: "flag Taiwan", k: "国旗 台湾", c: "flags" },
  { g: "🇹🇿", n: "flag Tanzania", k: "国旗 坦桑尼亚", c: "flags" },
  { g: "🇺🇦", n: "flag Ukraine", k: "国旗 乌克兰", c: "flags" },
  { g: "🇺🇬", n: "flag Uganda", k: "国旗 乌干达", c: "flags" },
  { g: "🇺🇲", n: "flag US Outlying Islands", k: "国旗", c: "flags" },
  { g: "🇺🇳", n: "flag United Nations", k: "旗帜 联合国", c: "flags" },
  { g: "🇺🇸", n: "flag United States", k: "国旗 美国", c: "flags" },
  { g: "🇺🇾", n: "flag Uruguay", k: "国旗 乌拉圭", c: "flags" },
  { g: "🇺🇿", n: "flag Uzbekistan", k: "国旗 乌兹别克斯坦", c: "flags" },
  { g: "🇻🇦", n: "flag Vatican City", k: "国旗 梵蒂冈", c: "flags" },
  { g: "🇻🇨", n: "flag St Vincent and Grenadines", k: "国旗", c: "flags" },
  { g: "🇻🇪", n: "flag Venezuela", k: "国旗 委内瑞拉", c: "flags" },
  { g: "🇻🇬", n: "flag British Virgin Islands", k: "国旗", c: "flags" },
  { g: "🇻🇮", n: "flag US Virgin Islands", k: "国旗", c: "flags" },
  { g: "🇻🇳", n: "flag Vietnam", k: "国旗 越南", c: "flags" },
  { g: "🇻🇺", n: "flag Vanuatu", k: "国旗 瓦努阿图", c: "flags" },
  { g: "🇼🇫", n: "flag Wallis and Futuna", k: "国旗", c: "flags" },
  { g: "🇼🇸", n: "flag Samoa", k: "国旗 萨摩亚", c: "flags" },
  { g: "🇽🇰", n: "flag Kosovo", k: "国旗 科索沃", c: "flags" },
  { g: "🇾🇪", n: "flag Yemen", k: "国旗 也门", c: "flags" },
  { g: "🇾🇹", n: "flag Mayotte", k: "国旗 马约特", c: "flags" },
  { g: "🇿🇦", n: "flag South Africa", k: "国旗 南非", c: "flags" },
  { g: "🇿🇲", n: "flag Zambia", k: "国旗 赞比亚", c: "flags" },
  { g: "🇿🇼", n: "flag Zimbabwe", k: "国旗 津巴布韦", c: "flags" },
];
